### DISCUSSION TITLE
Admission check on free resources

### DISCUSSION THREAD

**Discussion by bgedik** [kubernetes-sigs/kueue#2931] [Q&A] [answered]
I have a cluster where the batch workloads share nodes with non-batch workloads. When Kueue admits a workload, it is possible that the quota specified in the Kueue queue config indicates sufficient resources are available, but some of the nodes might be used by other workloads that do not use the batch scheduler. Is there an admission check that I can introduce to check availability of resources (based on free resources and not just quota declared) before admission?

**Comment by tenzen-y** [comment]
Kueue can check the actual Node usages before the Workloads are admitted by ProvisioningRequest.
Even if you use the fixed size cluster, you can use the capacity-check class ProvisioningRequest so that you can check the actual cluster resources.

**Reply by bgedik** [reply]
Thanks @tenzen-y . Where can I find more about the ProvisioningRequest classes? We are running on GKE.

**Reply by bgedik** [reply]
Basically, I need an AC like this I assume:

```
apiVersion: kueue.x-k8s.io/v1beta1
kind: AdmissionCheck
metadata:
  name: training-cluster-queue-ac
spec:
  controllerName: kueue.x-k8s.io/provisioning-request
  parameters:
    apiGroup: kueue.x-k8s.io
    kind: ProvisioningRequestConfig
    name: training-cluster-resource-prc
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ProvisioningRequestConfig
metadata:
  name: training-cluster-resource-prc
spec:
  provisioningClassName: capacity-check.???
  managedResources:
  - nvidia.com/gpu
```

Not sure what the `provisioningClassName` should be. 

Is it correct to assume that capacity-check check whether there are sufficient free resources to deploy all pods of the workload at this time?
