### DISCUSSION TITLE
Handling Long/Short Workloads in `AdmissionFairSharing`

### DISCUSSION THREAD

**Discussion by kimminw00** [kubernetes-sigs/kueue#5609] [Q&A] [answered]
~~We're currently exploring the use of `AdmissionFairSharing` to enable fair resource sharing across teams using separate `LocalQueue`s but targeting a shared `ClusterQueue`. The mechanism works well in principle, especially with configurations like:~~

-> Using individual `ClusterQueue` is the right approach to guarantee GPU quotas for each team/project.

```yaml
admissionFairSharing:
  usageHalfLifeTime: "168h"         # decay over 1 week
  usageSamplingInterval: "5m"       # sampled every 5 minutes
  resourceWeights:
    cpu: 1.0
    memory: 1.0
    nvidia.com/gpu: 2.0
```
However, we’re concerned about possible workload behaviors that might undermine fair sharing without triggering preemption, such as:

1. Long-running jobs that exceed the `usageHalfLifeTime` (e.g., 30 days) and monopolize resources, possibly delaying other workloads indefinitely. (Do long-running jobs that exceed the `usageHalfLifeTime` get penalized proportionally enough to ensure fair resource allocation?)

2. Many short-running jobs (e.g 10000 jobs) that run for less than the `usageSamplingInterval` (e.g., under 5 minutes), thereby avoiding being accounted in the usage metric. Lowering the `usageSamplingInterval` to capture these short-running jobs would likely put a significant load on kueue, potentially impacting its overall performance and stability.

Are there best practices to mitigate these patterns without enabling `preemption`?
