### ISSUE TITLE
[Job] Job could not borrow quota from the next Flavor

### ISSUE THREAD

**Issue by B1F030** [kubernetes-sigs/kueue#1276]
**What happened**:
![image](https://github.com/kubernetes-sigs/kueue/assets/77265354/ffa6aa27-7337-44d0-8271-718cfa957499)
When there is not enough nominal quota of resources in a ResourceFlavor, the incoming Workload could not borrow quota in the ClusterQueue or Cohort.

**What you expected to happen**:
The incoming Workload should borrow quota and turn to Running.

**How to reproduce it (as minimally and precisely as possible)**:
Here is my clusterQueue yaml:
```
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "flavor-fungibility-cq"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "x86"
      resources:
      - name: "cpu"
        nominalQuota: 500m
      - name: "memory"
        nominalQuota: 2Gi
    - name: "arm"
      resources:
      - name: "cpu"
        nominalQuota: 500m
      - name: "memory"
        nominalQuota: 2Gi
  flavorFungibility:
    whenCanBorrow: TryNextFlavor
    whenCanPreempt: Preempt
```
and my job yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  labels:
    kueue.x-k8s.io/queue-name: flavor-fungibility-queue
spec:
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:latest
        imagePullPolicy: IfNotPresent
        args: ["60s"]
        resources:
          requests:
            cpu: 500m
            memory: "500Mi"
      restartPolicy: Never
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.26.0
- Kueue version (use `git describe --tags --dirty --always`):
v0.5.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
manifests.yaml
- Others:

**Comment by alculquicondor** [comment]
I don't see a cohort defined for this ClusterQueue. And do you have a 2nd ClusterQueue?

**Comment by B1F030** [comment]
Thanks! I thought this "borrowing" can happen in one ClusterQueue without cohort...
Now I tried this on two ClusterQueue within one cohort, and it works!
By the way i can paste my yaml on, in case somebody else meet this situation as i do.

**Comment by B1F030** [comment]
`# cat arch-arm-cq.yaml`
```
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "arch-arm-cq"
spec:
  namespaceSelector: {} # match all.
  cohort: "arch"
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "arm"
      resources:
      - name: "cpu"
        nominalQuota: 500m
        borrowingLimit: 500m
      - name: "memory"
        nominalQuota: 2Gi
        borrowingLimit: 2Gi
    - name: "x86"
      resources:
      - name: "cpu"
        nominalQuota: 500m
        borrowingLimit: 500m
      - name: "memory"
        nominalQuota: 2Gi
        borrowingLimit: 2Gi
  flavorFungibility:
    whenCanBorrow: TryNextFlavor
    whenCanPreempt: Preempt
```
`# cat arch-x86-cq.yaml`
```
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "arch-x86-cq"
spec:
  namespaceSelector: {} # match all.
  cohort: "arch"
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "x86"
      resources:
      - name: "cpu"
        nominalQuota: 500m
        borrowingLimit: 500m
      - name: "memory"
        nominalQuota: 2Gi
        borrowingLimit: 2Gi
    - name: "arm"
      resources:
      - name: "cpu"
        nominalQuota: 500m
        borrowingLimit: 500m
      - name: "memory"
        nominalQuota: 2Gi
        borrowingLimit: 2Gi
  flavorFungibility:
    whenCanBorrow: TryNextFlavor
    whenCanPreempt: Preempt
```
`# cat sample-job.yaml `
```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  labels:
    kueue.x-k8s.io/queue-name: arch-arm-queue
spec:
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:latest
        imagePullPolicy: IfNotPresent
        args: ["60s"]
        resources:
          requests:
            cpu: 500m
            memory: "100Mi"
      restartPolicy: Never
```
