### ISSUE TITLE
Support preemption while borrowing

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1337]
**What would you like to be added**:

Enable preemption while borrowing. 

**Why is this needed**:

Today, preemption is not possible if it requires the CQ to borrow from another one.

There are scenarios where a globally shared quota is put in a separate ClusterQueue. In other words, every ClusterQueue in the cohort is borrowing from the shared CQ. Then, it is necessary to have preemption while borrowing, to be able to implement quality of service.

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by mimowo** [comment]
cc @alculquicondor 
/assign

**Comment by alculquicondor** [comment]
I think a possible API could look like this:

```yaml
preemption:
  borrowFromCohort:
    policy: Disable | LowerThanThreshold
    priorityThreshold
```
