### ISSUE TITLE
Plain Pod remains in Terminating state after deleting

### ISSUE THREAD

**Issue by nstogner** [kubernetes-sigs/kueue#1339]
**What happened**:

Deleting plain Pods managed by Kueue will hang in Terminating state forever.

**What you expected to happen**:

Expected Kueue to remove finalizer eventually and allow Pod to be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

Follow this guide: https://kueue.sigs.k8s.io/docs/tasks/run_plain_pods/

Delete Pod before it completes.

**Anything else we need to know?**:

Example of Pod that is hanging:

```yaml
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2023-11-16T22:10:10Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2023-11-16T22:10:29Z"
    finalizers:
    - kueue.x-k8s.io/managed
    labels:
      kueue.x-k8s.io/managed: "true"
      kueue.x-k8s.io/queue-name: xyz
    name: abc
    namespace: default
```

Did not see any errors in controller (even when raising log level to 3).

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3-gke.100", GitCommit:"6466b51b762a5c49ae3fb6c2c7233ffe1c96e48c", GitTreeState:"clean", BuildDate:"2023-06-23T09:27:28Z", GoVersion:"go1.20.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

- Kueue version (use `git describe --tags --dirty --always`):

`0.5.0`

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
