### ISSUE TITLE
Unable to delete pod group before admission

### ISSUE THREAD

**Issue by achernevskii** [kubernetes-sigs/kueue#1451]
**What happened**:

If I create 3 pods for a pod group of size 4 and then decide to delete it, there's no way for me to manually delete pods in the group, since all of the pods contain the finalizer.

**What you expected to happen**:

If all of the pods in the group have a deletion timestamp, the group is not finished, and there's no related workload, the pods should be finalized.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create 3 pods with `kueue.x-k8s.io/pod-group-total-count=4`:
   ```yaml
   apiVersion: v1
   kind: Pod
   metadata:
     generateName: kueue-sleep-
     annotations:
       kueue.x-k8s.io/pod-group-total-count: "4"
     labels:
       kueue.x-k8s.io/queue-name: user-queue
       kueue.x-k8s.io/pod-group-name: example-group
   spec:
     containers:
       - name: sleep
          image: busybox
          command:
           - sleep
         args:
           - 5m
         resources:
           requests:
             cpu: 1m
   ```

2. Delete all pods in the group:
   ```
   kubectl delete -l kueue.x-k8s.io/pod-group-name=example-group -n default
   ```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.28.3
- Kueue version (use `git describe --tags --dirty --always`): 
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
