### ISSUE TITLE
pytorchjobs scheduling unaware of node resource topology

### ISSUE THREAD

**Issue by kchopra456** [kubernetes-sigs/kueue#1476]
**What happened**:
- Kueue when handling distributed jobs, such as pytorchjob makes node-unaware admission decisions for dedicated resource such as GPUs.
- Even though the requested resource count may be available in aggregation, that does not translate to actual cluster physical resource availability, explained under.
  - 3 nodes with 8 GPU each, translates to 24 GPUs, all managed under kueue; initial cluster configuration is `8,8,8 GPUs`.
  - Admit 2 jobs, 1 GPU each, scheduled on 2 nodes; cluster configuration `7,7,8 GPUs`.
  - Submit a pytorchjob with 1 master and 1 worker, each requesting 8 GPU each, total requested GPUs 16.
  - Kueue allows this workload to be scheduled even though actual physical node topology would not schedule the job immediatedly and both the pods will sit in default k8s queue pending, waitiing for 1 more node to open (_partial admission not allowed_).

**What you expected to happen**:
- pytorchjob to remain suspended until 2 nodes i.e. 16 GPUs (8,8,X cluster configuration) is possible.
- A new job requesting a 8 GPU job should be able to schedule but with current implementation it waits suspended.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create kueue resources
```yaml
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: test-node
spec:
  nodeLabels:
    hpc/kueue-test: 'true' 

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: test-cq
spec:
  cohort: no-cohort
  namespaceSelector: {}
  resourceGroups:
    - coveredResources:
        - nvidia.com/gpu
      flavors:
        - name: test-node
          resources:
            - name: nvidia.com/gpu
              nominalQuota: '24'
              borrowingLimit: '0'

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: test-default
spec:
  clusterQueue: test-cq
```
2. Create jobs in the following sequence
   1. 1-GPU job (force it to node-001)
   2. 1-GPU job (force it to node-002)
   3. 16-GPU pytorchjob
   4. 8-GPU job
3. Use the template to create jobs and pytorchjob
`job.yaml`
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-001
  labels:
    kueue.x-k8s.io/queue-name: test-default
spec:
  template:
     spec:
      nodeName: node-00X
      containers:
        - name: main
          image: nginx:latest
          command:
            - sleep
            - '600'
          resources:
            limits:
              nvidia.com/gpu: "1"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  suspend: true
```
`pytorchjob.yaml`
```yaml
apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: pytorch-cq-001
  labels:
    kueue.x-k8s.io/queue-name: test-default
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: pytorch
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              command:
                - sleep
                - '600'
              resources:
                limits:
                  nvidia.com/gpu: "8"
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: nginx:latest
              imagePullPolicy: IfNotPresent
              command:
                - sleep
                - '600'
              resources:
                limits:
                  nvidia.com/gpu: "8"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  - cluster: v1.23
  - kubectl : v1.25
- Kueue version (use `git describe --tags --dirty --always`):
  - v0.5.0
- Cloud provider or hardware configuration:
  - Nvidia GPU
- OS (e.g: `cat /etc/os-release`):
  - Ubuntu 20.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
