### ISSUE TITLE
Support Kubeflow Jobs type for resource quota reclaim

### ISSUE THREAD

**Issue by panpan0000** [kubernetes-sigs/kueue#1503]
**What would you like to be added**:

reclaim the resource quota when kubeflow jobs(PytorchJob, TFJobs...etc) completed.
so far, when the Job CRD existing while the pod completed, the queue's flavorUsage will still be occupied , and stop incoming pods/jobs . 

```
#(1) show queue usage before job running 
kubectl  get localqueue -o yaml
    flavorUsage:
    - name: default-flavor
      resources:
      - name: cpu
        total: "1"
      - name: memory
        total: 2Gi
      - name: nvidia.com/gpu
        total: "1"

#(2) run a Pytorchjob with 3 pods which sleep for 1s, requesting 4c-2g-1GPU for each.
 kubectl  get po  -w
NAME                 READY   STATUS      RESTARTS   AGE
job-sleep-master-0   0/1     Completed   0          14s
job-sleep-worker-0   0/1     Completed   0          16s
job-sleep-worker-1   0/1     Completed   0          15s

 kubectl  get pytorchjob
NAME        STATE       AGE
job-sleep   Succeeded   4m32s


#(3)show queue usage again after job completed 
kubectl  get localqueue -o yaml
    flavorUsage:
    - name: default-flavor
      resources:
      - name: cpu
        total: "13"
      - name: memory
        total: 8Gi
      - name: nvidia.com/gpu
        total: "4"

```

**Why is this needed**:

it makes no sense to kill the xxjob right after finish, we still need the Pytorchjob CRD for some reason.
but kueue should reclaim the resource to reduce the `flavorUsage` after job completed.

relevant issue : https://github.com/kubernetes-sigs/kueue/issues/1149

**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kerthcet** [comment]
cc @kerthcet  @B1F030

**Comment by anishasthana** [comment]
@panpan0000 Do you have a sample job CR I could use for testing? I'd be happy to take a stab at this.

**Comment by panpan0000** [comment]
it's very easy to reproduce the issue but requires training-operator from kubeflow instsalled:
```
apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  annotations:
    baize.io/description: echo hostname
  labels:
    jobs.baize.io/training-mode: DISTRIBUTED
    kueue.x-k8s.io/queue-name: default-ns-local-queue
  name: echo-job
  namespace: default
spec:
  pytorchReplicaSpecs:
    Worker:
      replicas: 3
      template:
        metadata: {}
        spec:
          containers:
          - command: ["sleep", "1"]
            image: python:3.12.0
            name: pytorch
            resources:
              limits:
                cpu: "1"
                memory: 1Gi
                nvidia.com/gpu: 1
              requests:
                cpu: "1"
                memory: 1Gi
                nvidia.com/gpu: 1
  runPolicy:
    suspend: false
```
