### ISSUE TITLE
[Discussion] Consider pytorchJob cleanPodPolicy in kueue

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kueue#1574]
```
[root@flavor-1 yaml]# kubectl get pytorchjobs.kubeflow.org 
NAME                   STATE       AGE
pytorch-simple-td5kx   Succeeded   35s
```

```
[root@flavor-1 yaml]# kubectl get pod -o wide
NAME                            READY   STATUS      RESTARTS   AGE     IP              NODE       NOMINATED NODE   READINESS GATES
pytorch-simple-td5kx-master-0   0/1     Completed   0          2m31s   10.233.66.243   flavor-1   <none>           <none>
pytorch-simple-td5kx-worker-0   1/1     Running     0          2m31s   10.233.66.244   flavor-1   <none>           <none>
pytorch-simple-td5kx-worker-1   1/1     Running     0          2m31s   10.233.67.157   flavor-2   <none>           <none>
pytorch-simple-td5kx-worker-2   1/1     Running     0          2m31s   10.233.66.245   flavor-1   <none>           <none>
```

```
[root@flavor-1 yaml]# kubectl get localqueues.kueue.x-k8s.io local-queue -oyaml | grep flavorUsage -A 15
  flavorUsage:
  - name: default-flavor
    resources:
    - name: cpu
      total: "0"
  flavorsReservation:
  - name: default-flavor
    resources:
    - name: cpu
      total: "0"
  pendingWorkloads: 0
  reservingWorkloads: 0
```

With `spec.runPolicy.cleanPodPolicy=Running` unset, when job succeeds, the workers may still keep running, but kueue will reclaim the whole resources, which seems not rigorous. 

A better way seems like we should reclaim the completed pods rather than the whole job, but the tricky thing is it's hard for the kueue to aware of the individual Pods. At least, we should shout out this limitations.
