### ISSUE TITLE
Pod Groups: when a workload representing group of pods is readmitted then pods are not created

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1641]
**What happened**:

When a workload representing a group of pods is evicted, for example due to exceeding the timeout, and re-admitted, then the pods are not created. 

**What you expected to happen**:

Create replacement pods for the newly re-admitted workload.

Note that this is a different scenario than creating replacement pods for a running workload.

**How to reproduce it (as minimally and precisely as possible)**:

Install Kueue with "pod" integration enabled.

Also, enable `waitForReadyPods`, with `timeout: 1m`.

Create a cluster with the close to infinite quota:
```
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue-inf"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 10000
      - name: "memory"
        nominalQuota: 1000000Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue-inf"
spec:
  clusterQueue: "cluster-queue-inf"
```

Then, schedule the group of pods as follows:
```
apiVersion: v1
kind: Pod
metadata:
  generateName: sample-pod-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue-inf
    kueue.x-k8s.io/pod-group-name: "group"
  annotations:
    kueue.x-k8s.io/pod-group-total-count: "2"
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: dummy-job
    image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
    args: ["60s"]
    resources:
      requests:
        cpu: "1000"
        memory: "1Gi"
      limits:
        cpu: "1000"
        memory: "1Gi"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  generateName: sample-pod-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue-inf
    kueue.x-k8s.io/pod-group-name: "group"
  annotations:
    kueue.x-k8s.io/pod-group-total-count: "2"
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: dummy-job
    image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
    args: ["60s"]
    resources:
      requests:
        cpu: "1000"
        memory: "1Gi"
      limits:
        cpu: "1000"
        memory: "1Gi"
  restartPolicy: Never
```

The pods are pending (because we request 1000CPU (tune the value in case you have more :) ). 
Issue: after 1min the two pods are terminated, and the workload is preempted. 

**Issue:** the re-admitted workload does not create replacement pods.

Note that the similar case happens when the workload is re-admitted if it was preempted due to priority-based eviction.

**Anything else we need to know?**:

This is the example status of the `Terminating` pods:

```
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: null
      message: '0/2 nodes are available: 1 Insufficient cpu, 1 node(s) had untolerated
        taint {node-role.kubernetes.io/control-plane: }. preemption: 0/2 nodes are
        available: 1 No preemption victims found for incoming pod, 1 Preemption is
        not helpful for scheduling..'
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    - lastProbeTime: null
      lastTransitionTime: "2024-01-25T10:29:03Z"
      message: Exceeded the PodsReady timeout default/group
      reason: StoppedByKueue
      status: "True"
      type: TerminationTarget
    phase: Failed
    qosClass: Guaranteed
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
