### ISSUE TITLE
Using the same flavors in different resources might lead to unschedulable pods

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#167]
**What happened**:

When using the same flavors in multiple resources:

```yaml
  requestableResources:
  - name: "cpu"
    flavors:
    - resourceFlavor: x86
      quota:
        guaranteed: 9
    - resourceFlavor: arm
      quota:
        guaranteed: 12
  - name: "memory"
    flavors:
    - resourceFlavor: x86
      quota:
        guaranteed: 36Gi
    - resourceFlavor: arm
      quota:
        guaranteed: 48Gi
```

a workload could get admitted for cpu and memory with different flavors.

**What you expected to happen**:

workloads to get admitted to the same flavor for different resources.
