### ISSUE TITLE
Non-admitted workloads with QuotaReserved condition are shown as Admitted by kubectl

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1790]
**What happened**:

I have a workload in QuotaReserved condition, which is visible with kubectl describe:
```yaml
...
  Admission Checks:
    Last Transition Time:  2024-03-04T10:55:16Z
    Message:               
    Name:                  sample-multikueue
    State:                 Pending
  Conditions:
    Last Transition Time:  2024-03-04T10:55:16Z
    Message:               Quota reserved in ClusterQueue cluster-queue
    Reason:                QuotaReserved
    Status:                True
    Type:                  QuotaReserved
Events:
  Type    Reason         Age   From             Message
  ----    ------         ----  ----             -------
  Normal  QuotaReserved  43s   kueue-admission  Quota reserved in ClusterQueue cluster-queue, wait time since queued was 1s
```
However, the output of kubectl get suggests it is already admitted (I find this misleading):

```
> kubectl get workloads -owide                                                      
NAME                           QUEUE        ADMITTED BY     AGE
jobset-sleep-job-5xh9k-af81b   user-queue   cluster-queue   2m5s
```

**What you expected to happen**:

The output of kubectl get should clearly indicate that the workload is not admitted yet. Note that a workload may remain in the
QuotaReserved state for a long time.

One idea would be to have a new column "STATUS" which could have values: "Pending" "QuotaReserved", "Admitted".

**How to reproduce it (as minimally and precisely as possible)**:

Use admission check for ProvisioningRequest or MultiKueue, then the workload may stay in "QuotaReserved" state long enough to observe the discrepancy.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
