### ISSUE TITLE
Helm chart: setting `integrations.podOptions.namespaceSelector` results in webhook selector being erased

### ISSUE THREAD

**Issue by rhaps0dy** [kubernetes-sigs/kueue#1903]
**What happened**:

I added the following to `managerConfig.controllerManagerConfigYaml` in my Helm chart configuration:

```yaml
integrations:
  frameworks:
  - ...
  - "pod"
  podOptions:
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values: ["kube-system", "kueue-system"]
```

**What you expected to happen**:

The pod MutatingWebhook stays correct.

**How to reproduce it (as minimally and precisely as possible)**:

- modify the `managerConfig.controllerManagerConfigYaml` in `charts/kueue/values.yaml` to the value above. **Make sure that podOptions is a child of `integrations`, this has bitten me in the past.**

- Run:
```sh
helm template -n kueue-system my-release . less
```
and search for `mpod.kb.io` and `vpod.kb.io`. It looks like this:

```yaml
    name: mpod.kb.io
    namespaceSelector:    # <- NOTE: WRONG INDENTATION
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kueue-system
```

```yaml
    name: vpod.kb.io
    namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kueue-system

```

**Anything else we need to know?**:

To solve this, just change `nindent 4` to `nindent 6` in `add_webhook_pod_mutate` and `add_webhook_pod_validate` of `hack/update-helm.sh`, and in the corresponding part of the helm chart.
