### ISSUE TITLE
kueue controller lacks permission for configmaps.

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes-sigs/kueue#2094]
**What happened**:

kueue controller lacks permission for configmaps.

![image](https://github.com/kubernetes-sigs/kueue/assets/30817980/626ab068-f0e5-466a-9b1c-cd4dfd28b63b)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

I built the image based on commit 9890f41dfbdae.

Install kueue by:

kubectl apply --server-side -f https://github.com/kubernetes-sigs/kueue/releases/download/v0.6.2/manifests.yaml

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.28.3
- Kueue version (use `git describe --tags --dirty --always`): v0.6.2
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
@KunWuLuan This is curious. Could you investigate which operations we depend on the ConfigMap?
After that could you submit a PR?

Note that we manage the permissions by the kubebuilder markers like this:

https://github.com/kubernetes-sigs/kueue/blob/37c0943ab03c141d2d559decd44f29a98e76ce6d/pkg/controller/core/clusterqueue_controller.go#L144-L148

**Comment by alculquicondor** [comment]
/assign @mszadkow
could you investigate this?

**Comment by mszadkow** [comment]
@KunWuLuan could you provide more information on how to reproduce it?
Maybe what was the setup and installed packages?

**Comment by ukclivecox** [comment]
I had this issue when the namespace for the rolebinding for `kueue-visibility-server-auth-reader` was overwritten by kustomize to be `kueue-system` rather than `kube-system` as this is the one resource in the manifest which is not meant to be in the `kueue-system` namespace.

**Comment by botanical6748** [comment]
> I had this issue when the namespace for the rolebinding for `kueue-visibility-server-auth-reader` was overwritten by kustomize to be `kueue-system` rather than `kube-system` as this is the one resource in the manifest which is not meant to be in the `kueue-system` namespace.

I'm curious how you resolved this? I'm running into the same issue and am wondering if there is an update the default config that will prevent Kustomize from overwriting the namespace.

**Comment by ukclivecox** [comment]
I needed to add a patch to my kustomize

```
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: RoleBinding
      name: 'kueue-visibility-server-auth-reader'
    patch: |-
      - op: replace
        path: /metadata/namespace                                                                                      
        value: kube-system                                                                                             
      - op: replace                                                                                                    
        path: /subjects/0/namespace                                                                                    
        value: kueue-system                          
```
