### ISSUE TITLE
Unclear reason in Admitted condition when using admission checks

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2121]
**What would you like to be added**:

Currently, when a Workload has a quota reservation, but pending admission checks, the reason is `NoChecks`.

I suggest we `UnsatisfiedChecks` or `PendingChecks`. Similarly,
`NoReservationNoChecks` can be renamed to match the decision above.

The only tricky thing is that this is somewhat of a breaking change. Luckily, the strings didn't make it to the api package and both ProvisioningRequest and MultiKueue are alpha features.
I think we can change these.

**Why is this needed**:

`NoChecks` sounds ambiguous. There are checks, but they are not satisfied.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
@tenzen-y thoughts?

**Comment by alculquicondor** [comment]
Also it looks like the Admitted condition isn't always set:

https://github.com/kubernetes-sigs/kueue/blob/b088365f13ebc37d8e18d997b2a8d356b95c2d09/pkg/scheduler/scheduler.go#L517-520

I saw this outcome in a real cluster running v0.6.2

```yaml
status:
  admission:
    clusterQueue: dws-cluster-queue
    podSetAssignments:
    - count: 1
      flavors:
        cpu: default-flavor
        memory: default-flavor
        nvidia.com/gpu: default-flavor
      name: main
      resourceUsage:
        cpu: 100m
        memory: 100Mi
        nvidia.com/gpu: "1"
  admissionChecks:
  - lastTransitionTime: "2024-05-03T20:01:59Z"
    message: ""
    name: dws-prov
    state: Pending
  conditions:
  - lastTransitionTime: "2024-05-03T20:01:59Z"
    message: Quota reserved in ClusterQueue dws-cluster-queue
    reason: QuotaReserved
    status: "True"
    type: QuotaReserved
```
