### ISSUE TITLE
Pod group stuck in QuotaReserved after deactivated

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2222]
**What happened**:

A pod-group workload is stuck in QuotaReserved=True, with Evicted=False, after reaching the backoffLimit, when no replacement pods are sent.

This is likely because of this check
https://github.com/kubernetes-sigs/kueue/blob/ae5aaca92c5bff3c4bf06a0cbe3df2ecd72523fe/pkg/controller/jobframework/reconciler.go#L382

The pod group is considered suspended if there are no replacement pods.

That causes the reconciler to return before this:

https://github.com/kubernetes-sigs/kueue/blob/ae5aaca92c5bff3c4bf06a0cbe3df2ecd72523fe/pkg/controller/jobframework/reconciler.go#L417-L418

**What you expected to happen**:

The Evicted condition to transition to True.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install kueue with the following config:

```yaml
    waitForPodsReady:
      enable: true
      timeout: 30s
      requeuingStrategy:
        timestamp: Eviction
        backoffLimitCount: 1
```

2. Apply `examples/admin/single-clusterqueue-setup.yaml`

3. Run this pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-in-group
  labels:
    kueue.x-k8s.io/queue-name: user-queue
    kueue.x-k8s.io/pod-group-name: "sample-group"
  annotations:
    kueue.x-k8s.io/pod-group-total-count: "1"
spec:
  restartPolicy: Never
  nodeSelector:
    foo: doesnotexist
  containers:
  - name: sleep
    image: busybox
    command: ["sh", "-c", 'echo "hello world from the leader pod" && sleep 3']
    resources:
      requests:
        cpu: 3
```

**Anything else we need to know?**:

This issue is likely fixed with #2131, so we need to cherry-pick it to the 0.6 release.

But we should also add an integration test for the pod integration that exercises the case of not sending replacement pods.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`): `gcr.io/k8s-staging-kueue/kueue:v20240501-v0.6.2-12-g0a69bb7`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
