### ISSUE TITLE
MPIJobs can't run with ProvisioningRequest with DWS

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#2260]
**What happened**:

For DWS, we use the following configuration:

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ProvisioningRequestConfig
metadata:
  name: dws-config
spec:
  provisioningClassName: queued-provisioning.gke.io
  managedResources:
  - nvidia.com/gpu
```

This allows to create a ProvReq only for the workers of an MPIJob, but not the launcher.

However, when the ProvisioningRequest is satisfied, the Kueue provisioning controller only sets a `podSetUpdate` for the podset used in the provisioningRequest. This fails validation for the Workload status.

**What you expected to happen**:

Validation should pass for cases where `podSetUpdates` has less elements than `.spec.podSets` and the logic that handles the updates should not expect the slices to match.

**How to reproduce it (as minimally and precisely as possible)**:

- Configure a cluster using https://cloud.google.com/kubernetes-engine/docs/how-to/provisioningrequest#for_jobs_with_kueue
- Create an MPIJob where the workers requests GPUs, but the launcher doesn't.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
