### ISSUE TITLE
[FairSharing] ClusterQueue status does not report stats

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2422]
**What happened**:

When using FairSharing, the ClusterQueue.status.fairSharing field remains empty even if the ClusterQueue is borrowing.

**What you expected to happen**:

The ClusterQueue.status.fairSharing.weightedShare to be updated as soon as the cluster queue starts borrowing.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster like this:
```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cq-a"
spec:
  cohort: "cohort"
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cq-b"
spec:
  cohort: "cohort"
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cq-c"
spec:
  cohort: "cohort"
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "queue-a"
spec:
  clusterQueue: "cq-a"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "queue-b"
spec:
  clusterQueue: "cq-b"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "queue-c"
spec:
  clusterQueue: "cq-c"
```
Then create 4 Jobs like this:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  labels:
    kueue.x-k8s.io/queue-name: queue-a
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
        args: ["10m"]
        resources:
          requests:
            cpu: "1"
            memory: "200Mi"
      restartPolicy: Never
```
Then, inspect the clusterqueue-a:
```yaml
status:
  admittedWorkloads: 4
  conditions:
  - lastTransitionTime: "2024-06-17T10:24:20Z"
    message: Can admit new workloads
    observedGeneration: 1
    reason: Ready
    status: "True"
    type: Active
  fairSharing: {}
  flavorsReservation:
  - name: default-flavor
    resources:
    - borrowed: "3"
      name: cpu
      total: "12"
    - borrowed: "0"
      name: memory
      total: 2400Mi
  flavorsUsage:
  - name: default-flavor
    resources:
    - borrowed: "3"
      name: cpu
      total: "12"
    - borrowed: "0"
      name: memory
      total: 2400Mi
  pendingWorkloads: 0
  reservingWorkloads: 4
```
Issue: `status.fairSharing.weightedShare` is empty.
