### ISSUE TITLE
Kueue with Jobset automatically suspends child job

### ISSUE THREAD

**Issue by tiffzhao5** [kubernetes-sigs/kueue#2612]
**What happened**:

I'm running a simple Jobset with Kueue, and even a Kueue Workload doesn't get created (i.e. `kubectl get workloads` returns nothing found). If I run a batchv1Job with Kueue, a Workload gets successfully admitted. Is there something wrong with the configuration I'm using?

**What you expected to happen**:

A Jobset with Kueue should create a Workload and get admitted to the LocalQueue.

**How to reproduce it (as minimally and precisely as possible)**:
In `kueue.yaml`, I define the `ResourceFlavor`, `ClusterQueue`, and `LocalQueue`: 

```
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "spot"
spec:
  nodeLabels:
    node-lifecycle: normal
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory", "pods"]
    flavors:
    - name: "spot"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
      - name: "pods"
        nominalQuota: 5
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: default
  name: test-queue
spec:
  clusterQueue: cluster-queue 
```

I define a `Jobset` through `jobset_example.yml`:

```
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: sleep-job
  labels:
    kueue.x-k8s.io/queue-name: test-queue
  
spec:
  failurePolicy:
    maxRestarts: 4
  replicatedJobs:
    - name: workers
      replicas: 1
      template:
        spec:
          template:
            spec:
              nodeSelector:
                node-lifecycle: normal
              containers:
                - name: quick-container
                  image: busybox
                  command: ["/bin/sh", "-c"]
                  args: ["sleep 1"]
```

I apply both `kubectl apply -f kueue.yaml` and `kubectl apply -f jobset_example.yml`, and no Kueue Workload is even created, where `kubectl get workloads --all-namespaces` gives me:

```
No resources found
```

When I do `kubectl describe job -n default sleep-job-workers-0`, I see the following events:

```
Events:
  Type    Reason            Age                   From                        Message
  ----    ------            ----                  ----                        -------
  Normal  SuccessfulDelete  4m9s                  job-controller              Deleted pod: sleep-job-workers-0-0-sm2gt
  Normal  SuccessfulCreate  4m9s                  job-controller              Created pod: sleep-job-workers-0-0-sm2gt
  Normal  SuccessfulCreate  4m8s                  job-controller              Created pod: sleep-job-workers-0-0-slnjd
  Normal  Suspended         4m8s (x8 over 4m9s)   job-controller              Job suspended
  Normal  SuccessfulCreate  4m8s                  job-controller              Created pod: sleep-job-workers-0-0-nq7vd
  Normal  SuccessfulDelete  4m8s                  job-controller              Deleted pod: sleep-job-workers-0-0-nq7vd
  Normal  SuccessfulCreate  4m8s                  job-controller              Created pod: sleep-job-workers-0-0-k9qhf
  Normal  SuccessfulDelete  4m8s                  job-controller              Deleted pod: sleep-job-workers-0-0-k9qhf
  Normal  Suspended         4m8s (x25 over 4m9s)  batch/job-kueue-controller  Kueue managed child job suspended
  Normal  SuccessfulDelete  4m8s                  job-controller              Deleted pod: sleep-job-workers-0-0-slnjd
  Normal  SuccessfulCreate  4m8s                  job-controller              Created pod: sleep-job-workers-0-0-cqvfc
  Normal  Resumed           4m8s (x3 over 4m8s)   job-controller              Job resumed
  Normal  SuccessfulDelete  4m8s                  job-controller              Deleted pod: sleep-job-workers-0-0-cqvfc
  Normal  SuccessfulCreate  4m8s                  job-controller              Created pod: sleep-job-workers-0-0-2h7vn
  Normal  SuccessfulDelete  4m8s                  job-controller              Deleted pod: sleep-job-workers-0-0-2h7vn
  Normal  SuccessfulCreate  4m8s                  job-controller              Created pod: sleep-job-workers-0-0-nmm8w
  Normal  SuccessfulDelete  4m8s                  job-controller              Deleted pod: sleep-job-workers-0-0-nmm8w
```    

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```

- Kueue version (use `git describe --tags --dirty --always`):
Installed Kueue via helm charts:

`kubectl describe deployment kueue-controller-manager -n kueue-system` gives:

```
Name:                   kueue-controller-manager
Namespace:              kueue-system
CreationTimestamp:      Thu, 06 Jun 2024 22:41:23 +0100
Labels:                 app.kubernetes.io/instance=kueue
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=kueue
                        app.kubernetes.io/version=v0.7.0
                        control-plane=controller-manager
                        helm.sh/chart=kueue-0.1.0
                        node-lifecycle=persistent
                        node-purpose=system
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: kueue
                        meta.helm.sh/release-namespace: kueue-system
Selector:               app.kubernetes.io/instance=kueue,app.kubernetes.io/name=kueue,control-plane=controller-manager,node-lifecycle=persistent,node-purpose=system
```

- Cloud provider or hardware configuration:
Kueue and Jobset deployments are both running on AWS instances, and Jobsets created are also running on AWS instances that have the node label `node-lifecycle:normal`

- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
