### ISSUE TITLE
Document how to use Kueue for Deployments

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2677]
**What would you like to be added**:

A new page showing how Kueue can be used for Deployments. 

It can be a new sub-page "Run Deployments" this page: https://kueue.sigs.k8s.io/docs/tasks/run/.

I have tested that Deployments can already be supported with Kueue via the Plain pods integration:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        kueue.x-k8s.io/queue-name: user-queue
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 3
```

This allows to scale up and scale down the deployment, which should be mentioned in the docs.

**Note**: this requires enabling the "pod" integration, and setting the queue-name at the pod template level. We are considering making this easier for the users: webhook to copy the user-name  down to template, dedicated "deployment" integration in kueue config, 

However, this issue is just about documenting the status quo which would already works for users on 0.6+. Once the improvements are done we can extend the docs with the appropriate notes.

**Why is this needed**:

To increase awareness among users who would like to use Kueue for serving / AI inference workloads.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Docs update

The artifacts should be linked in subsequent comments.
