### ISSUE TITLE
Support Structured Parameters (DRA) in Kueue

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/kueue#2941]
**What would you like to be added**:
Workloads should be able to use Resource Claims in their specs and Kueue should be aware of this when doing quota management.
**Why is this needed**:
Support DRA.
**Completion requirements**:

This enhancement requires the following artifacts:

- [x] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kannon92** [comment]
Hoping to maybe discuss first what has been done with DRA. I can help with a KEP once we have a path forward.

@alculquicondor @tenzen-y Have either of you looked into how Kueue would work with DRA resources?

https://github.com/kubernetes-sigs/dra-example-driver/tree/main/demo

has a list of a few examples of how structured parameters works.

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  namespace: gpu-test1
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: gpu
  resourceClaims:
  - name: gpu
    resourceClaimTemplateName: gpu.example.com
```

Containers would now have a claim and the resourceClaimTemplate would dictate exactly what is being requested. It seems that there may be some indirection Kueue would need to take to support this.

**Comment by alculquicondor** [comment]
Nothing has been done for DRA :)

**Comment by alculquicondor** [comment]
The only other related issue is #1538

**Comment by tenzen-y** [comment]
This looks great! 
@kannon92 Which will you take the DRA? Classic DRA? or DRA with structured parameters?

**Comment by alculquicondor** [comment]
Classic DRA is likely getting removed in the next few versions, so I wouldn't like to invest on it in Kueue.

**Comment by kannon92** [comment]
Hey @tenzen-y. From the source (https://github.com/kubernetes/enhancements/issues/3063#issuecomment-2302065085), Classic DRA may be dropped in 1.32 so I will go with structured parameters

**Comment by tenzen-y** [comment]
I agree with you.
In that case, we can somehow take the exact resource amount from the ResourceSlice object.
Although, we maybe want to tackle to handle ResourceSlice object as the separate features.

It would be great if you could consider the future ResourceSlice collaboration in this design.
In other words, I don't want to block the possibility of collaborating with Kueue and ResourceSlice with this ResourceClaim feature.

**Comment by kannon92** [comment]
/retitle Support Structured Parameters (DRA) in Kueue

**Comment by kannon92** [comment]
I think the API I use is what I need to research. Going to retitle as I don't have a clear direction yet.

**Comment by kannon92** [comment]
So @tenzen-y you are saying that something like:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test4

---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test4
  name: multiple-gpus
spec:
  spec:
    devices:
      requests:
      - name: gpus
        deviceClassName: gpu.example.com
        allocationMode: ExactCount
        count: 4

---
apiVersion: v1
kind: Pod
metadata:
  namespace: gpu-test4
  name: pod0
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: ubuntu:22.04
    command: ["bash", "-c"]
    args: ["export; sleep 9999"]
    resources:
      claims:
      - name: gpus
  resourceClaims:
  - name: gpus
    resourceClaimTemplateName: multiple-gpus
```

In this case, if a resourceClaimTemplate is using an allocationMode of ExactCount, that may be easier to support.

@alculquicondor @tenzen-y I'm open to suggestions on how you want to tackle DRA support in Kueue. We could piece by piece it or we create a KEP walking through the different options?
