### ISSUE TITLE
[MultiKueue] AdmissionCheck conditions are confusing

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3094]
**What happened**:

I got feedback from a user running into an issue with MultiKueue, and getting distracted by confusing AdmissionCheck conditions, and wasting time during investigations.

```yaml
  - lastTransitionTime: "2024-09-07T10:27:28Z"
      message: only one multikueue managed admission check can be used in one ClusterQueue
      observedGeneration: 1
      reason: MultiKueue
      status: "True"
      type: SingleInstanceInClusterQueue
    - lastTransitionTime: "2024-09-07T10:27:28Z"
      message: admission check cannot be applied at ResourceFlavor level
      observedGeneration: 1
      reason: MultiKueue
      status: "True"
      type: FlavorIndependent
```

**What you expected to happen**:

No user-facing conditions used by MultiKueue for its inner-workings.

**How to reproduce it (as minimally and precisely as possible)**:

Setup MultiKueue according to https://kueue.sigs.k8s.io/docs/tasks/manage/setup_multikueue/. 

**Anything else we need to know?**:

The mechanism was introduced as part of [Single instance admission check.](https://github.com/kubernetes-sigs/kueue/pull/1635#top)(https://github.com/kubernetes-sigs/kueue/pull/1635), but the solution based on status conditions was contested and deferred to be revisted on future releases https://github.com/kubernetes-sigs/kueue/pull/1635#discussion_r1466659290. 

I propose to:
- drop the conditions, and hard-code dependencies between built-in Admission checks, as suggested in the [comment](https://github.com/kubernetes-sigs/kueue/pull/1635#discussion_r1466659290). This approach will also let us easily implement https://github.com/kubernetes-sigs/kueue/issues/2021
- move the user-facing configuration as part of the support for external Admission Checks (I can open a follow up issue for this)
