### ISSUE TITLE
[PartialAdmission] Job does not reclaim free resources properly if partially admitted

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3141]
**What happened**:

Free resources are reclaimed with unnecessary delay when using partial admission.

**What you expected to happen**:

Allow to use free resources as soon as available.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the following config:

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 9
      - name: "memory"
        nominalQuota: 36Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "user-queue"
spec:
  clusterQueue: "cluster-queue"
```
2. Submit the small.yaml Job:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["1800s"]
        resources:
          requests:
            cpu: "1"
            memory: "200Mi"
      restartPolicy: Never
```
3. create the `big.yaml`:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-big-
  labels:
    kueue.x-k8s.io/queue-name: user-queue
  annotations:
    kueue.x-k8s.io/job-min-parallelism: "3"
spec:
  parallelism: 9
  completions: 9
  completionMode: Indexed
  suspend: true
  template:
    spec:
      containers:
      - name: job-longrun
        image: python
        command:
        - python3
        - -c
        - |
          import os
          import time
          import sys
          id = int(os.environ.get("JOB_COMPLETION_INDEX"))
          time.sleep(5 + id*5)
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1"
            memory: "200Mi"
      restartPolicy: Never
```
Then, monitoring the usage of the CQ:
```
> k get cq -w --output-watch-events -ocustom-columns="TYPE:.type,NAME:.object.metadata.name,USAGE:.object.status.flavorsUsage[0].resources[0].total" | ts "%H:%M:%.S"
11:30:02.801519 TYPE    NAME            USAGE
11:30:02.801689 ADDED   cluster-queue   0
11:30:28.388297 MODIFIED   cluster-queue   3
11:30:42.878975 MODIFIED   cluster-queue   9
11:31:29.980804 MODIFIED   cluster-queue   8
11:31:40.010289 MODIFIED   cluster-queue   7
11:31:50.030854 MODIFIED   cluster-queue   3
```

Notably, the drop of usage (7->3) in the last two lines corresponds to just one pod completing. In other words when the declared usage is 7, there are only 4 pods running (1 from big, and 3 from small workload).

**Anything else we need to know?**:

I tested a fix for the scenario locally by changing this line: https://github.com/kubernetes-sigs/kueue/blob/23dec6d1d1f1a0e8fa51bb63349af84f6f52d9dd/pkg/controller/jobs/job/job_controller.go#L229 to 
`Count: j.Status.Succeeded`. I believe this makes sense as a fix. It would also be consistent with formulas for other job CRDs, like JobSet.
