### ISSUE TITLE
Unexpected preemption between ClusterQueues within a Cohort

### ISSUE THREAD

**Issue by octotocat** [kubernetes-sigs/kueue#3210]
**What happened**:
In a setup where three ClusterQueues (Q1, Q2, and Q3) are part of the same cohort, we observed that a high-priority workload (WL3) from Q3 preempted a low-priority workload (WL1) from Q1, despite preemption policies being configured to prevent this. Specifically:
- `reclaimWithinCohort: Never`
- `borrowWithinCohort.policy: Never`
- `withinClusterQueue: LowerPriority`

**What you expected to happen**:
WL3 should have remained pending because:
- The preemption policies (`reclaimWithinCohort: Never` and `borrowWithinCohort.policy: Never`) should have prevented resource reclamation across ClusterQueues within the same cohort.
- There was no candidate for preemption within Q1 based on the preemption policy (`withinClusterQueue: LowerPriority`).

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up three ClusterQueues (Q1, Q2, Q3) in the same cohort with the following preemption policies:
   - `reclaimWithinCohort: Never`
   - `borrowWithinCohort.policy: Never`
   - `withinClusterQueue: LowerPriority`
2. Assign 8 GPUs in total to the cluster.
3. Submit 4-GPU low-priority workloads (WL1 and WL2) to Q1 and Q2, respectively.
4. Submit a 4-GPU high-priority workload (WL3) to Q3 and admit it.
5. Observe that WL3 preempts WL1, despite the preemption policy setup.

**Anything else we need to know?**:
It appears the preemption policy does not fully respect the cohort-level restrictions, allowing WL3 to preempt WL1, which contradicts the configured settings.
WL1 Status/Events did not log the preemption. Kueue immediately started a new WL1-1 for the deployment and WL1 was evicted. It occurred to WL1 or WL2 randomly. Attached Kueue controller logs during the event happened. In this log [kueue_logs.txt](https://github.com/user-attachments/files/17319516/kueue_logs.txt), WL2 was evicted. 
This unexpected preemption behavior also occurs between cohorts. According to the documentation, preemption should never happen between cohorts.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27.2
- Kueue version (use `git describe --tags --dirty --always`): v0.8.1
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools: helm
- Others:

test.yaml: 
```
apiVersion: v1
kind: Namespace
metadata:
  name: dac-resv-1
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "dac-resv-1"
spec:
  namespaceSelector: {} # match all.
  cohort: cohort-dedicated
  preemption:
    reclaimWithinCohort: Never
    borrowWithinCohort:
      policy: Never
    withinClusterQueue: LowerPriority
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: "default-flavor"
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 4
              borrowingLimit: 0
              lendingLimit: 0
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: dac-resv-1
  name: dac-resv-1
spec:
  clusterQueue: dac-resv-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dac-resv1-deployment
  namespace: dac-resv-1
spec:
  replicas: 1
  selector:
    matchLabels:
      kueue-job: "true"
  template:
    metadata:
      labels:
        kueue-job: "true"
        kueue.x-k8s.io/queue-name: dac-resv-1
    spec:
      priorityClassName: low-priority-class
      containers:
        - name: pod-dac-resv-1
          image: busybox
          command: ["sh", "-c", "sleep infinity"]
          ports:
            - containerPort: 80
          resources:
            requests:
              nvidia.com/gpu: "4"
            limits:
              nvidia.com/gpu: "4"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - 10.0.101.70
---
apiVersion: v1
kind: Namespace
metadata:
  name: dac-resv-2
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "dac-resv-2"
spec:
  namespaceSelector: {} # match all.
  cohort: cohort-dedicated
  preemption:
    reclaimWithinCohort: Never
    borrowWithinCohort:
      policy: Never
    withinClusterQueue: LowerPriority
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: "default-flavor"
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 4
              borrowingLimit: 0
              lendingLimit: 0
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: dac-resv-2
  name: dac-resv-2
spec:
  clusterQueue: dac-resv-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dac-resv2-deployment
  namespace: dac-resv-2
spec:
  replicas: 1
  selector:
    matchLabels:
      kueue-job: "true"
  template:
    metadata:
      labels:
        kueue-job: "true"
        kueue.x-k8s.io/queue-name: dac-resv-2
    spec:
      priorityClassName: low-priority-class
      containers:
        - name: pod-dac-resv-2
          image: busybox
          command: ["sh", "-c", "sleep infinity"]
          ports:
            - containerPort: 80
          resources:
            requests:
              nvidia.com/gpu: "4"
            limits:
              nvidia.com/gpu: "4"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - 10.0.101.70
---
apiVersion: v1
kind: Namespace
metadata:
  name: dac-resv-3
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "dac-resv-3"
spec:
  namespaceSelector: {} # match all.
  cohort: cohort-dedicated
  preemption:
    reclaimWithinCohort: Never
    borrowWithinCohort:
      policy: Never
    withinClusterQueue: LowerPriority
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: "default-flavor"
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 4
              borrowingLimit: 0
              lendingLimit: 0
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: dac-resv-3
  name: dac-resv-3
spec:
  clusterQueue: dac-resv-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dac-resv3-deployment
  namespace: dac-resv-3
spec:
  replicas: 1
  selector:
    matchLabels:
      kueue-job: "true"
  template:
    metadata:
      labels:
        kueue-job: "true"
        kueue.x-k8s.io/queue-name: dac-resv-3
    spec:
      priorityClassName: high-priority-class
      containers:
        - name: pod-dac-resv-3
          image: busybox
          command: ["sh", "-c", "sleep infinity"]
          ports:
            - containerPort: 80
          resources:
            requests:
              nvidia.com/gpu: "4"
            limits:
              nvidia.com/gpu: "4"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - 10.0.101.70
```
WL1:
```
apiVersion: kueue.x-k8s.io/v1beta1
kind: Workload
metadata:...
status:...
spec:
  active: true
  podSets:...
  priority: 10
  priorityClassName: low-priority-class
  priorityClassSource: scheduling.k8s.io/priorityclass
  queueName: dac-resv-1
```
Other setups:
Installed Kueue from helm chart. 
Integrated with "pod" in Values.integrations.frameworks. 
Enabled "waitForPodsReady" with "blockAdmission". 
Did not enable fairSharing.
