### ISSUE TITLE
Add resource limits into ResourceGroup of ClusterQueue/Cohort

### ISSUE THREAD

**Issue by FillZpp** [kubernetes-sigs/kueue#3215]
**What would you like to be added**:

Maybe a `limits` field that can be added into `ResourceGroup` struct for `ClusterQueue` or the new `Cohort` CRD.

Like this:

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
spec:
  cohort: "foo"
  resourceGroups:
  - coveredResources: ["cpu", "memory", "nvidia.com/gpu"]
    limits:
      # maybe also limits to cpu/memory
      nvidia.com/gpu: 16
    flavors:
    - name: "group-0"
      resources:
      - name: "cpu"
        nominalQuota: 64
      - name: "memory"
        nominalQuota: 128Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 8
    - name: "group-1"
      resources:
      - name: "cpu"
        nominalQuota: 32
      - name: "memory"
        nominalQuota: 64Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 4
```

**Why is this needed**:

What we want is that even we have several flavors in a `ResourceGroup` which all have different nominalQuota/borrowingLimit and can borrow from another ClusterQueue with the same cohort, but we still need an overall limit for this `ResourceGroup` including all flavors used in it.

Does it make sense?

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.
