### ISSUE TITLE
Cannot find CA bundle to use for Prometheus scraper with TLS verification enabled.

### ISSUE THREAD

**Issue by rvasahu-amazon** [kubernetes-sigs/kueue#3259]
Hi, hope you're well.

I'm trying to set up a Prometheus scraper to access the Kueue metrics endpoint.

```
---
# create configmap for prometheus scrape config
apiVersion: v1
data:
  # prometheus config
  prometheus.yaml: |
    global:
      scrape_interval: 1m
      scrape_timeout: 10s
    scrape_configs:
    - job_name: 'kueue_metrics'
      scheme: https
      tls_config:
        insecure_skip_verify: false
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
...
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring-ns
```

Since this needs to be productionised, ideally we'd like `insecure_skip_verify` under `tls_config` to be false. I understand that the scraper would need a CA bundle corresponding to the CA that was used to create the self-signed cert for TLS handshake. There isn't much Kueue documentation I can find on this, so I'm having trouble determining how to find and use this cert.

I have a couple questions:
1. Is there a CA bundle somewhere that would contain a cert for the metrics endpoint? I could then presumably mount and use the bundle. Alternatively, how should I get a cert for subject `kueue-controller-manager-metrics-service.kueue-system.svc.cluster.local`?
2. Is it possible that using TLS verification for accessing the metrics endpoint is not a supported use-case? For example, I can see [this](https://github.com/kubernetes-sigs/kueue/blob/587a6fc6f87072685ae7a64d6652b713fa78d790/charts/kueue/templates/prometheus/monitor.yaml#L15) service monitor does not use TLS verification:

```
...
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
...
```

I would appreciate your insight. Thanks in advance for your help, much appreciated.
