### ISSUE TITLE
JobSet stays in suspend state if kueue is managing it

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/kueue#3349]
**What happened**:
If I submit a simple JobSet with kueue, the workload stays in a suspend state.
**What you expected to happen**:
Kueue will unsuspend and the workload will run successfully.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: paralleljobs
  namespace: kueue-demo
  labels:
    kueue.x-k8s.io/queue-name: queue
spec:
  replicatedJobs:
  - name: workers
    replicas: 2
    template:
      spec:
        parallelism: 4
        completions: 4
        backoffLimit: 0
        template:
          spec:
            containers:
            - name: sleep
              image: quay.io/quay/busybox
              command: 
                - sleep
              args:
                - 100s
  - name: driver
    template:
      spec:
        parallelism: 1
        completions: 1
        backoffLimit: 0
        template:
          spec:
            containers:
            - name: sleep
              image: quay.io/quay/busybox
              command: 
                - sleep
              args:
                - 100s

```

1) Submit a jobset that uses kueue (ie add  Workload will stay in a suspended state.

**Anything else we need to know?**:
JobSet is 0.7.0.
**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`): 0.8.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
