### ISSUE TITLE
TAS: may report negative values of pods in messages for non-admitted workloads

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3482]
**What happened**:

When a workload using preferred topology annotation cannot be admitted is sometimes reports negative number of pods in the status message of the workload.

**What you expected to happen**:

negative values of pods are never reported, it does not make sense.

**How to reproduce it (as minimally and precisely as possible)**:

I have a reproducible scenario, but it is yet not simplified enough to be included here. I will simplify and post.

Basically I create multiple jobs using preferred, and workload corresponding to the non-admitted job reports message like:
```
status:
  conditions:
  - lastTransitionTime: "2024-11-07T13:01:01Z"
    message: 'couldn''t assign flavors to pod set main: insufficient unused quota
      for cpu in flavor tas-flavor, 30 more needed, topology "gke-default" allows
      to fit only -18 out of 40 pod(s)'
    observedGeneration: 1
    reason: Pending
    status: "False"
    type: QuotaReserved
```

**Anything else we need to know?**:

It was reported first here: https://github.com/kubernetes-sigs/kueue/issues/3211#issuecomment-2458900114
