### ISSUE TITLE
reclaimWithinCohort preemption does not work with hierarchical cohorts

### ISSUE THREAD

**Issue by kaschnit** [kubernetes-sigs/kueue#3948]
**What happened**:

I set up a simple 2-level hierarchical cohort using the Cohorts API. I was unable to get preemptions to happen via `reclaimWithinCohort` to work using the hierarchy.

The following Cohort and ClusterQueue setup:
```
- Cohort(name=root, nominalQuota=0m)
  - ClusterQueue(name=best-effort, nominalQuota=0m)
  - Cohort(name=guaranteed, nominalQuota=100m)
    - ClusterQueue(name=guaranteed, nominalQuota=0m)
```

Note that the "guaranteed" ClusterQueue should effectively have a nominal quota of 100m cpu since it belongs to the guaranteed cohort. Also note that the "guaranteed" ClusterQueue was configured with `spec.preemption.reclaimWithinCohort=Any`.

The following happened
1. Submitted Job(name=best-effort, cpu=100m) to a LocalQueue pointing at ClusterQueue "best-effort"
2. Waited for job "best-effort" to start running
3. Submitted Job(name=guaranteed, cpu=100m) to a LocalQueue pointing at ClusterQueue "guaranteed"
4. Job "guaranteed" is not scheduled until job "best-effort" completes and terminates itself (not terminated via preemption)

No preemption happens even though I think my configuration suggests that it should.

**What you expected to happen**:

The "best-effort" job is borrowing the entire quota from the "guaranteed" cohort, so the "guaranteed" job which belongs to the "guaranteed" cohort should be able to reclaim the quota via preemption.

I expect that the "guaranteed" job should preempt the "best-effort" job.

**How to reproduce it (as minimally and precisely as possible)**:

Kueue config:

```yaml
---
# Empty resource flavor
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default
---
# Root Cohort
apiVersion: kueue.x-k8s.io/v1alpha1
kind: Cohort
metadata:
  name: root
spec:
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default"
      resources:
      - name: "cpu"
        nominalQuota: "0m"
---
# Guaranteed Cohort
apiVersion: kueue.x-k8s.io/v1alpha1
kind: Cohort
metadata:
  name: guaranteed
spec:
  parent: root
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default"
      resources:
      - name: "cpu"
        nominalQuota: "100m"
---
# Guaranteed ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "guaranteed"
spec:
  namespaceSelector: {}
  preemption:
    reclaimWithinCohort: Any
    borrowWithinCohort:
      policy: Never
    withinClusterQueue: Never
  cohort: guaranteed
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default"
      resources:
      - name: "cpu"
        nominalQuota: "0m"
---
# Best-effort ClusterQueues
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "best-effort"
spec:
  namespaceSelector: {}
  preemption:
    reclaimWithinCohort: Never
    borrowWithinCohort:
      policy: Never
    withinClusterQueue: Never
  cohort: root
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default"
      resources:
      - name: "cpu"
        nominalQuota: "0m"
---
# LocalQueues
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: guaranteed
spec:
  clusterQueue: guaranteed
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: best-effort
spec:
  clusterQueue: best-effort
```

Best-effort job:

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: best-effort-
  labels:
    kueue.x-k8s.io/queue-name: best-effort
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["180s"]
        resources:
          requests:
            cpu: "100m"
      restartPolicy: Never
```

Guaranteed job:

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: guaranteed-
  labels:
    kueue.x-k8s.io/queue-name: guaranteed
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["30s"]
        resources:
          requests:
            cpu: "100m"
      restartPolicy: Never
```

To reproduce:
1. Apply the kueue config
2. Create the "best-effort" job
3. Wait for Kueue to admin the "best-effort" job and create its pod.
4. Submit the "guaranteed" job. You will see that no preemptions happen.

**Anything else we need to know?**:

It is worth noting that I saw the "guaranteed" job start to preempt the "best-effort" job when I made the following changes:

1.  Created two `WorkloadPriorityClass`es, low (value=50) and high(value=100)
2. Assigned these priority classes to the "best-effort" and "guaranteed" jobs respectively
3. Set `spec.preemption.borrowWithinCohort.policy=LowerPriority` on the "guaranteed" ClusterQueue

This also seems incorrect, because it would seem to mean that the "guaranteed" Cohort is borrowing quota from the "root" Cohort, which should not be possible because the "root" Cohort has 0 nominal quota. I'm happy to provide the exact configuration and repro steps if needed.

Please let me know if you need any more information from me. Thank you kindly.

**Environment**:
- Kubernetes version (use `kubectl version`): client v1.25.2, server v1.32.0
- Kueue version (use `git describe --tags --dirty --always`): v0.11.0-devel-40-gbf4657ad
- Cloud provider or hardware configuration: kind cluster on my laptop
- OS (e.g: `cat /etc/os-release`): MacOS Catalina
- Kernel (e.g. `uname -a`): Darwin Kernel Version 19.6.0
- Install tools:
- Others: installed kueue with helm on a kind cluster, nothing else installed on the cluster
