### ISSUE TITLE
Kueue (v0.10.0) does not run in a restricted security namespace even though it could

### ISSUE THREAD

**Issue by rhaps0dy** [kubernetes-sigs/kueue#3958]
In `main`, this is now fixable without editing the chart, because the `kube-rbac-proxy` has been removed as deprecated. **But**  it still won't work without setting the policy to be stricter in `values.yaml`, and we might as well do that by default.

I tried fixing this before with PR #2105 but @alculquicondor asked "why does root filesystem need to be writeable?" I have now investigated, and the reason is that `apiserver.crt` and `apiserver.key` are written to `/tmp`. 

I have a PR which updates #2105 , updates it with an emptyDir on `/tmp`. I will make it if it is wanted.

**What happened**:

I upgraded to kueue v0.10.0 (from my custom fork). Then, the kueue pods cannot be created because the `kube-rbac-proxy` violates the restricted podSecurityPolicy.

**What you expected to happen**:

It deploys fine.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy kueue v0.10.0 using the Helm chart in a restricted security namespace. Make sure to use:
```
    podSecurityContext:
      seccompProfile:
        type: "RuntimeDefault"
      runAsNonRoot: true
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
```
