### ISSUE TITLE
Fail to enable batch jobs

### ISSUE THREAD

**Issue by octotocat** [kubernetes-sigs/kueue#4043]
Kueue controller manager container failed to start if I enable batch: 
Config refers to https://kueue.sigs.k8s.io/docs/tasks/manage/setup_wait_for_pods_ready/
```
managerConfig:
  controllerManagerConfigYaml: |-
...
  waitForPodsReady:
      enable: true
      timeout: 5m
      blockAdmission: true
      requeuingStrategy:
        timestamp: Eviction | Creation
        backoffLimitCount: 5 # null indicates infinite requeuing
        backoffBaseSeconds: 60
        backoffMaxSeconds: 3600
```
with pod integration: 
``` 
   integrations:
      frameworks:
      - "pod"
      - "deployment"
      podOptions:
        namespaceSelector:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values: [ kube-system, kueue-system ]
            - key: kueue-job
              operator: In
              values: [ "true", "True", "yes" ]
```
Error: Back-off restarting failed container manager in pod kueue-controller-manager-xxx. No container log as container failed to start. 
Any clue? 
Version: v0.10.1. 
Same config used to work with v0.8.1. After upgraded to v10, didn't work, and when I downgraded to v8 again, still didn't work.
