### ISSUE TITLE
Kueue workloads admitted but jobs remain suspended

### ISSUE THREAD

**Issue by eskaug** [kubernetes-sigs/kueue#406]
**What happened**:
Kueue workloads correctly show admission, but jobs remain suspended and no pods are created.

**What you expected to happen**:
Job should be unsuspended, and pod created to begin work.

**How to reproduce it (as minimally and precisely as possible)**:
My nodes are labeled individually to match my ResourceFlavor labels:
```
kubectl label nodes node1 flavor-label=flavor-label-1
kubectl label nodes node2 flavor-label=flavor-label-2
kubectl label nodes node3 flavor-label=flavor-label-3
kubectl label nodes node4 flavor-label=flavor-label-4
```

resourcelabels.yaml
```
apiVersion: kueue.x-k8s.io/v1alpha2
kind: ResourceFlavor
metadata:
  name: flavor-1
  labels:
    flavor-label: flavor-label-1
---
apiVersion: kueue.x-k8s.io/v1alpha2
kind: ResourceFlavor
metadata:
  name: flavor-2
  labels:
    flavor-label: flavor-label-2
---
apiVersion: kueue.x-k8s.io/v1alpha2
kind: ResourceFlavor
metadata:
  name: flavor-3
  labels:
    flavor-label: flavor-label-3
---
apiVersion: kueue.x-k8s.io/v1alpha2
kind: ResourceFlavor
metadata:
  name: flavor-4
  labels:
    flavor-label: flavor-label-4
```

ClusterQueue references the same resource flavors, and includes resource limits.
clusterqueues.yaml
```
apiVersion: kueue.x-k8s.io/v1alpha2
kind: ClusterQueue
metadata:
  name: shared-clusterqueue
spec:
  cohort: my-cohort
  namespaceSelector: {}
  queueingStrategy: BestEffortFIFO
  resources:
  - name: "cpu"
    flavors:
    - name: flavor-1
      quota:
        min: "1.15"
    - name: flavor-2
      quota:
        min: "2"
    - name: flavor-3
      quota:
        min: "2"
    - name: flavor-4
      quota:
        min: "2"
---
apiVersion: kueue.x-k8s.io/v1alpha2
kind: LocalQueue
metadata:
  namespace: default
  name: shared-queue
spec:
  clusterQueue: shared-clusterqueue
```

1.1-job.yaml
```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-1.1-
  annotations:
    kueue.x-k8s.io/queue-name: shared-queue
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:latest
        args: ["3600s"]
        resources:
          requests:
            cpu: 1.1
      restartPolicy: Never
```

**Anything else we need to know?**:
Notes: I have attempted to simplify my setup a little bit by only including one resource type, though we are hoping to use both CPU and memory constraints.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:26:47Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Kueue version (use `git describe --tags --dirty --always`):
`kubectl describe -n kueue-system deployment.apps/kueue-controller-manager`:
```
  Containers:
   manager:
    Image:      gcr.io/k8s-staging-kueue/kueue:v0.2.1
```
- Cloud provider or hardware configuration:
On-prem cluster including 4 identical VMs.  Each has 2 CPUs and 15.5G RAM
- OS (e.g: `cat /etc/os-release`):
CentOS 7.9.2009 Core
- Kernel (e.g. `uname -a`):
I don't have direct access to the host machines, but if more details are relevant here I will work to get them.
- Install tools:
- Others:
