### ISSUE TITLE
Consider a diff image for testing/samples

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes-sigs/kueue#43]
I am running into 
```bash
  Warning  Failed     11s   kubelet            Failed to pull image "perl": rpc error: code = Unknown desc = reading manifest latest in docker.io/library/perl: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
we might want to consider an image out of a diff registry to avoid this unfortunate error 

/kind test

**Comment by ArangoGutierrez** [comment]
I have this one 
`quay.io/eduardoarango/pi:ubi8`
This is the repo -> https://github.com/ArangoGutierrez/Pi

``bash
[eduardo@fedora kueue]$ kubectl logs sample-job--1-24kpr

 1000 trials, pi is 3.120000 
```

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  generateName: sample-job-
  annotations:
    kueue.x-k8s.io/queue-name: main
spec:
  parallelism: 3
  completions: 30
  suspend: true
  template:
    spec:
      containers:
      - name: pi
        image: quay.io/eduardoarango/pi:ubi8
        command: ["pi",  "1000"]
        resources:
          requests:
            cpu: 1
            memory: "200Mi"
          limits:
            cpu: 1
            memory: "200Mi"
      restartPolicy: Never
```
