### ISSUE TITLE
WaitForPodsReady: support deleting workload when backoffLimitCount is reached

### ISSUE THREAD

**Issue by avrittrohwer** [kubernetes-sigs/kueue#4471]
**What would you like to be added**:

Add support for having Kueue delete the Kueue Workload and underlying workload object (Job, JobSet, etc) when the WaitForPodsReady backoffLimitCount is reached.

We could add a RequeuingStrategy.ttlSecondsAfterBackoffLimitReached field.

**Why is this needed**:

Currently, when the backoffLimitCount is reached, the workload sits with condition DeactivatedDueToRequeuingLimitExceeded.  This is a terminal state for the workload.  Some underlying workload APIs support a time-to-live mechanism that causes the workload to be deleted some time after reaching a terminal state.  For example JobSet has ttlSecondsAfterFinished.  A JobSet that reaches the backoffLimitCount in Kueue never enters a terminal state from the JobSet point of view (just sits as suspended).  So customers need to write some controller to watch Kueue workloads with DeactivatedDueToRequeuingLimitExceeded and delete the underlying workload object (or do this manually).

**Completion requirements**:

Have some way for workloads reaching the DeactivatedDueToRequeuingLimitExceeded condition to be automatically cleaned up.

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by avrittrohwer** [comment]
Here is a workaround deployment I tested in a kind cluster to clean up JobSets in this state.  **IT HAS NOT BEEN TESTED AT SCALE, BUYER BEWARE**. 

Kubernetes manifests:

```
apiVersion: v1
kind: Namespace
metadata:
  name: kueue-cleaner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kueue-cleaner
  name: kueue-cleaner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: kueue-cleaner
  name: kueue-cleaner-role
rules:
- apiGroups: ["kueue.x-k8s.io", "jobset.x-k8s.io"]
  resources: ["workloads", "jobsets"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kueue-cleaner-binding
subjects:
- kind: ServiceAccount
  namespace: kueue-cleaner
  name: kueue-cleaner-sa
roleRef:
  kind: ClusterRole
  name: kueue-cleaner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kueue-cleaner
  name: kueue-cleaner
  labels:
    app: kueue-cleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kueue-cleaner
  template:
    metadata:
      labels:
        app: kueue-cleaner
    spec:
      serviceAccountName: kueue-cleaner-sa
      containers:
      - name: kueue-cleaner
        image: <YOUR_IMAGE>
        command:
        - "python"
        - "/usr/src/app/main.py"
        # uncomment to start deleting - "--no-dry-run"
```

Dockerfile:

```
FROM python:3.13

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "/usr/src/app/main.py" ]
```

requirements.txt:

```
cachetools==5.5.2
certifi==2025.1.31
charset-normalizer==3.4.1
durationpy==0.9
google-auth==2.38.0
idna==3.10
kubernetes==32.0.1
oauthlib==3.2.2
pyasn1==0.6.1
pyasn1_modules==0.4.1
python-dateutil==2.9.0.post0
PyYAML==6.0.2
requests==2.32.3
requests-oauthlib==2.0.0
rsa==4.9
six==1.17.0
urllib3==2.3.0
websocket-client==1.8.0
```

main.py:

```
import argparse
import json
import kubernetes
import logging
import sys
import time


logger = logging.getLogger(__name__)


def retry_wait(prev_timeout):
    min_timeout = 3
    max_timeout = 60
    factor = 1.5
    
    if prev_timeout < min_timeout:
        timeout = min_timeout
    else:
        timeout = int(prev_timeout * factor) # int() only works if the min_timeout * factor is greater than 2 (otherwise we keep getting 1).

    if timeout > max_timeout:
        timeout = max_timeout

    logger.info(f"Sleeping for {timeout} seconds due to retry")
    time.sleep(timeout)
    return timeout


def should_delete_workload(workload):
    for condition in workload["status"]["conditions"]:
        if condition["reason"] == "DeactivatedDueToRequeuingLimitExceeded" and condition["status"] == 'True':
            for owner in workload["metadata"]["ownerReferences"]:
                if owner["apiVersion"] == "jobset.x-k8s.io/v1alpha2" and owner["kind"] == "JobSet":
                    return True, workload["metadata"]["namespace"], owner["name"]

    return False, "", ""


def delete_jobset(api, namespace, name):
    try:
        api.delete_namespaced_custom_object(
            "jobset.x-k8s.io", "v1alpha2", namespace, "jobsets", name,
            grace_period_seconds=0)
        logger.info(f"Deleted jobset {namespace}/{name}")
    except kubernetes.client.rest.ApiException as e:
        # ignore not found
        if e.status == 404:
            return
        logger.error(f"Error deleting JobSet {namespace}/{name}: {e}")


def watch_workloads(api, poll_frequency_seconds, list_limit, dry_run):
    retry_timeout = 0
    def increment_timeout():
        nonlocal retry_timeout
        retry_timeout = retry_wait(retry_timeout)
    def reset_timeout():
        nonlocal retry_timeout
        retry_timeout = 0

    continue_token = ""
    while True:
        time.sleep(retry_timeout)    
        try:
            ret = api.list_custom_object_for_all_namespaces(
                "kueue.x-k8s.io", "v1beta1", "workloads",
                _continue=continue_token,
                limit=list_limit,
                timeout_seconds=30)
            reset_timeout()
        except kubernetes.client.rest.ApiException as e:
            if e.status == 410:
                try:
                    body = json.loads(e.body)
                except json.decoder.JSONDecodeError:
                    logger.error(f"Got HTTP 410 error listing Workloads but could not load HTTP body as JSON. Original error: {e}")
                    increment_timeout()
                    continue

                # 410 is treated as successful response, we just need to start with the new continue token.
                continue_token = body["metadata"]["continue"]
                reset_timeout()
                continue
                    
            logger.error(f"Error listing Workloads: {e}")
            increment_timeout()
            continue
        
        for workload in ret["items"]:
            should_delete, namespace, jobset_name = should_delete_workload(workload)
            if should_delete:
                if dry_run:
                    logger.info(f"(--dry_run enabled) Would delete jobset {namespace}/{jobset_name}")
                    continue
                # Don't retry deletion here, we will try again on the next list.
                delete_jobset(api, namespace, jobset_name)

        if ret["metadata"]["continue"] != "":
            continue_token = ret["metadata"]["continue"]
            continue

        continue_token = ""
        time.sleep(poll_frequency_seconds)


def main():
    logging.basicConfig(stream=sys.stderr, level=logging.INFO, format="%(asctime)s %(name)s:%(lineno)d %(levelname)s:%(message)s", datefmt='%Y-%m-%dT%H:%M:%S%z')

    p = argparse.ArgumentParser()
    p.add_argument('--poll-frequency-seconds', type=int, default=60)
    p.add_argument('--list-batch-size', type=int, default=64)
    p.add_argument('--dry-run', type=bool, default=True, action=argparse.BooleanOptionalAction)
    args = p.parse_args()
    logger.info(f"Args: {args}")
    
    try:
        kubernetes.config.load_incluster_config()
    except kubernetes.config.ConfigException:
        kubernetes.config.load_kube_config()

    api = kubernetes.client.CustomObjectsApi()
    logger.info("Starting to watch Kueue Workloads...")
    watch_workloads(api, args.poll_frequency_seconds, args.list_batch_size, args.dry_run)


if __name__ == "__main__":
    main()
```

**Comment by mimowo** [comment]
I think deleting workloads which are deactivated sounds very useful. Such workloads will likely never be able to run, and would need manual cleanup by an admin, or script (as above). This is indeed a very similar case to deleting finished workloads, so a similar API is my natural intuition, but let's consider options:
1. a dedicated extension to the waitForPodsReady API, such as `ttlSecondsAfterBackoffLimitReached` under `waitForPodsReady.requeingStrategy`
2. a extension to the API in https://github.com/kubernetes-sigs/kueue/pull/2742, for example
or more granular:
```
objectRetentionPolicies:
  finishedWorkloadRetention: 10min
  deactivatedWorkloadRetention: 10min
```
```yaml
objectRetentionPolicies:
  finishedWorkloadRetention: 10min
  deactivatedWorkloadRetentionPolicy:
    - reason: RequeuingLimitExceeded
       ttl: 10min
    - reason: MaximumExecutionTimeExceeded
       ttl: 30min
    - reason: DeactivatedDueToAdmissionCheck
       ttl: 3min
```
I would be leaning to (2.) because it feels more natural given the similar nature of the feature (global TTL), just with different preconditions on the objects. I admit (2.) carries a bit more work, but it does not feel like much more.

Wdyt @tenzen-y @avrittrohwer ?

**Comment by avrittrohwer** [comment]
Adding support for cleaning up deactivated workloads via KEP 1628 sounds good to me

**Comment by mimowo** [comment]
Ok, regarding the two options (a) and (b) under 2, maybe we do a mix:
```yaml
objectRetentionPolicies:
  finishedWorkloads: 
     ttl: 10min
  deactivatedWorkloads:
     ttl: 10min
```
for now, but with this proposal:
- we don't do full "b" yet - because we don't have an indication that we need different ttl depending on the reason of deactivation
- we make the `finishedWorkloads` and `deactivatedWorkloads` structs. so they can be easily extended in future if needed (for example with different ttl depending on the reason)
- don't put "Retention" on both levels, because it is redundant

wdyt? Or maybe instead of "ttl" we use "defaultTTL", but I guess the details can be discussed in the KEP itself.

**Comment by yugantrana** [comment]
The proposed option seems sufficient for the initial implementation, and we can always extend it to something like (b) later if the need arises.

A note regarding default values,
- It would be beneficial to have `objectRetentionPolicies.deactivatedWorkloads.ttl` default to 0. 
- This would mean deactivated workloads are cleaned up immediately unless a user explicitly sets a different deactivatedWorkloads' TTL.

**Comment by mimowo** [comment]
> It would be beneficial to have objectRetentionPolicies.deactivatedWorkloads.ttl default to 0.

Yeah, maybe, the issue is it would be a breaking change. So, I would prefer a backwards compatible API (no TTL), or at least some higher value like 1h.

**Comment by tenzen-y** [comment]
For the future expansion, I would like to select

```yaml
objectRetentionPolicies:
  workloads:
    afterFinished: 10m
  admissionChecks: # no plan for now
```

Anyway, we need to disscuss this in a KEP
