### ISSUE TITLE
GKE RayJob's ProvisioningRequests fail unless RayJob deleted when AdmissioCheck fails for GPU node resources

### ISSUE THREAD

**Issue by ukclivecox** [kubernetes-sigs/kueue#4544]
I have set a a GKE auto-scaling node-pool for GPUs with max nodes 1. If I start 3 RayJobs one will suceed but the other 2 ProvisionRequests will fail. This is solved by deleting the COMPLETED RayJob after which the ProvisionRequests can suceed. Is this expected? I would assume as the GKE node pool scales down to 0 nodes after completion of the RayJob the ProvisionRequests can succeed (1 at a time)?

Config below 

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "dws"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: AdmissionCheck
metadata:
  name: dws-prov
spec:
  controllerName: kueue.x-k8s.io/provisioning-request
  parameters:
    apiGroup: kueue.x-k8s.io
    kind: ProvisioningRequestConfig
    name: dws-config
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ProvisioningRequestConfig
metadata:
  name: dws-config
spec:
  provisioningClassName: queued-provisioning.gke.io
  managedResources:
  - nvidia.com/gpu
  retryStrategy:
    backoffLimitCount: 10
    backoffBaseSeconds: 30
    backoffMaxSeconds: 3600  
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "my-cluster-queue"
spec:
  namespaceSelector: {} 
  resourceGroups:
  - coveredResources: ["cpu", "memory", "nvidia.com/gpu", "ephemeral-storage"]
    flavors:
    - name: "dws"
      resources:
      - name: "cpu"
        nominalQuota: 10000  # Infinite quota.
      - name: "memory"
        nominalQuota: 10000Gi # Infinite quota.
      - name: "nvidia.com/gpu"
        nominalQuota: 1000000000  # Infinite quota.
      - name: "ephemeral-storage"
        nominalQuota: 10000Ti # Infinite quota.
  admissionChecks:
  - dws-prov
---

```
