### ISSUE TITLE
TAS: workloads with nodeSelectors are scheduled by TAS, but not kube-scheduler

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#4571]
**What happened**:

When using explicit nodeSelectors in the Job / Workload spec the pods might not be able to scheduled by kube-scheduler, even though they are scheduled by TAS.

**What you expected to happen**:

TAS will restrict the set of considered leaf domains (nodes) only to those which match the specified node selectors.
Similarly, as we restrict the set of considered nodes based on taints and tolerations.

**How to reproduce it (as minimally and precisely as possible)**:

Create the TAS setup:

```yaml
kind: ResourceFlavor
apiVersion: kueue.x-k8s.io/v1beta1
metadata:
  name: "tas-flavor"
spec:
  nodeLabels:
    kubernetes.io/os: "linux"
  topologyName: "default"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "tas-cluster-queue"
spec:
  namespaceSelector: {} # match all.
  resourceGroups:
  - coveredResources: ["cpu", "memory"]
    flavors:
    - name: "tas-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 200 
      - name: "memory"
        nominalQuota: 200Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: "default"
  name: "tas-user-queue"
spec:
  clusterQueue: "tas-cluster-queue"
---
apiVersion: kueue.x-k8s.io/v1alpha1
kind: Topology
metadata:
  name: "default"
spec:
  levels:
  - nodeLabel: "kubernetes.io/hostname"
```
2. create a Job with a node selector, eg.

```yaml
apiVersion: batch/v1
kind: Job 
metadata:
  generateName: tas-sample-small-required-host-
  labels:
    kueue.x-k8s.io/queue-name: tas-user-queue
spec:
  parallelism: 2
  completions: 2
  completionMode: Indexed
  template:
    metadata:
      annotations:
        kueue.x-k8s.io/podset-required-topology: "kubernetes.io/hostname"
    spec:
      nodeSelector:
        kubernetes.io/hostname: "kind-worker3"
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["1800s"]
        resources:
          requests:
            cpu: "1" 
            memory: "200Mi"
      restartPolicy: Never
```

Result, the workload is scheduled, but the pods remain suspended;

```
> k get pods -owide
NAME                                           READY   STATUS            RESTARTS   AGE     IP       NODE     NOMINATED NODE   READINESS GATES
tas-sample-small-required-host-t29tv-0-fldzf   0/1     SchedulingGated   0          4m35s   <none>   <none>   <none>           <none>
tas-sample-small-required-host-t29tv-1-2d97m   0/1     SchedulingGated   0          4m35s   <none>   <none>   <none>           <none>
```

**Anything else we need to know?**:

We already solve the similar problem for taints and tolerations. PTAL: https://github.com/kubernetes-sigs/kueue/blob/843e4df0a871cb83d0e1ed0b26bbe6f65e171a06/pkg/cache/tas_flavor_snapshot.go#L621-L628
