### ISSUE TITLE
kep-4377: Document how one can implement secure metrics

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/kueue#4575]
A user can either enable this with kustomize code or they can use the helm chart.

```yaml
metrics:
  prometheusNamespace: monitoring
# tls configs for serviceMonitor
  serviceMonitor:
    tlsConfig:
      serverName: kueue-controller-manager-metrics-service.kueue-system.svc
      insecureSkipVerify: false
      ca:
        secret:
          name: kueue-metrics-server-cert
          key: ca.crt
      cert:
        secret:
          name: kueue-metrics-server-cert
          key: tls.crt
      keySecret:
        name: kueue-metrics-server-cert
        key: tls.key
```

We should add an example in our installation guide to make it clear that we support secure metrics.
