### ISSUE TITLE
High-Priority Workload Fails to Preempt Lower-Priority Workload Using Borrowed Resources

### ISSUE THREAD

**Issue by dora-zhang** [kubernetes-sigs/kueue#4597]
**Problem Description**
I found a high-priority workload (`h1`) in ClusterQueue `cq-hi` cannot preempt a lower-priority workload (`m2`) in ClusterQueue `cq-med`, despite both being in the same cohort. The situation is as follows:
ClusterQueue `cq-med`:
   - Has reserved resources from ResourceFlavor `rf1`
   - Can borrow resources from ResourceFlavor `rf2`

ClusterQueue `cq-hi`:
  - Enabled to borrow from both `rf1` and `rf2`

**Steps to Reproduce**
1. Cluster Setup:

a. ResourceFlavors:
- rf1 (1 GPU)
- rf2 (1 GPU)

b. Create two ClusterQueues:
- cq-med
```
spec:
  cohort: common
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  preemption:
    borrowWithinCohort:
      policy: LowerPriority
    reclaimWithinCohort: Any
    withinClusterQueue: LowerPriority
  queueingStrategy: BestEffortFIFO
  stopPolicy: None
  resourceGroups:
    - flavors:
        - name: rf1
          resources:
            - name: nvidia.com/gpu
              nominalQuota: 1  # Reserved 1 GPU
        - name: rf2
          resources:
            - name: nvidia.com/gpu
              nominalQuota: 0  # Enable borrow
```
- cq-high
```
spec:
  [omit same setting as cq-med]
  resourceGroups:
    - flavors:
        - name: rf1
          resources:
            - name: nvidia.com/gpu
              nominalQuota: 0  # Enable borrow
        - name: rf2
          resources:
            - name: nvidia.com/gpu
              nominalQuota: 0  # Enable borrow
```
2. Workload Setup:
- `m1`, `m2`: Each requests 1 GPU, medium priority
- `h1`: Requests 1 GPU, high priority

3. Execution Steps:
a. Submit workloads `m1` and `m2` to `cq-med`:
Result: Successfully scheduled
- `m1` occupies the reserved GPU from `rf1`
- `m2` occupies the borrowed GPU from `rf2`

b. Submit workload `h1` to `cq-high`:
Result: `h1` remains pending, unable to preempt lower-priority workloads
Error message:
`Warning  Pending  16m (x7 over 36m)  kueue-admission  couldn't assign flavors to pod set main: insufficient unused quota for nvidia.com/gpu in flavor rf1, 1 more needed, insufficient unused quota for nvidia.com/gpu in flavor rf2, 1 more needed`

**Expected vs Actual Results** 
•	I was expected: High-priority workload h1 should preempt lower-priority workloads `m2` to claim the GPU.
•	Actual: High-priority workload is stuck in Pending state.

**Questions** 
1.	Observation: When assigning a Flavor to workload `h1`, the code selects `rf1` as a candidate but not `rf2`.
a. Why is `rf1` preferred over `rf2` in this scenario?
b. Should the assignment logic prioritize borrowed resources (rf2) over reserved resources (rf1) when looking for preemption candidates?

2. I'm further looking into this function `PotentialAvailable`, I'm not quite clear how the potential available is calculated. How does Kueue handle resource visibility across `ClusterQueues` with shared `ResourceFlavors`?

Additional information for crd configuration
resourceFlavor
```
#  kubectl get rf -o yaml
apiVersion: v1
items:
- apiVersion: kueue.x-k8s.io/v1beta1
  kind: ResourceFlavor
  metadata:
…
    name: ng1
    …
  spec:
    nodeLabels:
…
    tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists
- apiVersion: kueue.x-k8s.io/v1beta1
  kind: ResourceFlavor
  metadata:
…
    name: ng2
…
  spec:
    nodeLabels:
      …
    tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists
kind: List
metadata:
  resourceVersion: ""
```

ClusterQueue Configuration:
```
# kubectl get cq cq-med -o yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
….
  name: cq-med
  …
spec:
  cohort: memverge.ai
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  namespaceSelector:
    matchLabels:
      project: cq-med
  preemption:
    borrowWithinCohort:
      policy: LowerPriority
    reclaimWithinCohort: Any
    withinClusterQueue: LowerPriority
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources:
    - cpu
    - memory
    - nvidia.com/gpu
    flavors:
    - name: ng1
      resources:
      - name: cpu
        nominalQuota: "0"
      - name: memory
        nominalQuota: "0"
      - name: nvidia.com/gpu
        nominalQuota: "1"
    - name: ng2
      resources:
      - name: cpu
        nominalQuota: "0"
      - name: memory
        nominalQuota: "0"
      - name: nvidia.com/gpu
        nominalQuota: "0"
  stopPolicy: None
Status:
…
```

```
# kubectl get cq cq-hi -o yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  ..
  name: cq-hi
  ..
spec:
  cohort: memverge.ai
  flavorFungibility:
    whenCanBorrow: Borrow
    whenCanPreempt: TryNextFlavor
  namespaceSelector:
    matchLabels:
      project: cq-hi
  preemption:
    borrowWithinCohort:
      policy: LowerPriority
    reclaimWithinCohort: Any
    withinClusterQueue: LowerPriority
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources:
    - cpu
    - memory
    - nvidia.com/gpu
    flavors:
    - name: ng1
      resources:
      - name: cpu
        nominalQuota: "0"
      - name: memory
        nominalQuota: "0"
      - name: nvidia.com/gpu
        nominalQuota: "0"
    - name: ng2
      resources:
      - name: cpu
        nominalQuota: "0"
      - name: memory
        nominalQuota: "0"
      - name: nvidia.com/gpu
        nominalQuota: "0"
  stopPolicy: None
```

**Comment by xiongzubiao** [comment]
This seems a bug that can happen whenever 2+ resourceflavors are used, even there is only 1 queue (no borrowing). 

Considering the following simple ClusterQueue:
```
spec:
  preemption:
    withinClusterQueue: LowerPriority  # <== enable priority-based preemption
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: rf1
      resources:
      - name: cpu
        nominalQuota: 1
    - name: rf2
      resources:
      - name: cpu
        nominalQuota: 1
```

Firstly let's submit two workloads (each requesting 1 cpu) one by one to this queue: 1) `wl-high` with high priority first. It will be assigned to `rf1`. 2) then `wl-low` with low priority will be assigned to `rf2`.

Now let's submit the third workload `wl-medium` with medium priority. It is expected that it can be assigned to `rf2` and preempt `wl-low`. But it doesn't happen, even in version v0.11.0-rc.0.

cc @gabesaba @mimowo
