### ISSUE TITLE
RF nodeTaints do not work well couple with RF tolerations

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#4646]
**What happened**:
If we specify the same labels to `.spec.nodeTaints` and `.spec.tolerations` in the ResourceFlavor, `nodeTaints` does not work well. As a result, unexpected RF will be assigned to Workload without tolerations.

**What you expected to happen**:
If the Workload does not have `tolerations` corresponding to RF nodeTaints, the RF with nodeTaints is not assigned to the Workload.

https://kueue.sigs.k8s.io/docs/concepts/resource_flavor/#resourceflavor-taints

**How to reproduce it (as minimally and precisely as possible)**:
We could imagine the following RF. Even if the Workload does not have "spot" tolerations, the flavor-assigner considers that the Workload can be scheduled since the assigner assumes the Worklod can be accommodated by tolerations propagating from RF `.spec.tolerations` to Workload in the following mechanism.

https://github.com/kubernetes-sigs/kueue/blob/0009c097f4720289e88f68540ab1344bba1bd7a8/pkg/scheduler/flavorassigner/flavorassigner.go#L541-L543

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "flavor"
  nodeTaints:
  - effect: NoSchedule
    key: spot
    value: "true"
  tolerations:
  - key: spot
    operator: "Exists"
    effect: "NoSchedule"
```

**Anything else we need to know?**:
I think that the possible fix is just adding validations for RFs so that they can not specify the same taints/tolerations in the same RF.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
> I think that the possible fix is just adding validations for RFs so that they can not specify the same taints/tolerations in the same RF.

@gabesaba @PBundyra @mimowo Do you have alternative better solutions?

**Comment by tenzen-y** [comment]
This change came from https://github.com/kubernetes-sigs/kueue/pull/3722 and was shipped to v0.9.2, v0.10.0, and later.

**Comment by PBundyra** [comment]
I'm not sure where the issue is - I believe it WAI

**Comment by PBundyra** [comment]
After all, workloads will inherit tolerations from the RF, so effectively they should be able to schedule on the nodes with corresponding taints

**Comment by mimowo** [comment]
> We could imagine the following RF. Even if the Workload does not have "spot" tolerations, the flavor-assigner considers that the Workload can be scheduled since the assigner assumes the Worklod can be accommodated by tolerations propagating from RF .spec.tolerations to Workload in the following mechanism.

Yeah, this is WAI imo as well. The `.spec.tolerations` are added during admission of Workload, so they allow the workload to run inspite of the node taints. Since the workload can run there is no need to artificially block it during scheduling.

**Comment by tenzen-y** [comment]
> After all, workloads will inherit tolerations from the RF, so effectively they should be able to schedule on the nodes with corresponding taints

They should not specify the same key and values both to `nodeTaints` and `nodeSelectors` since they have conflict.
As we can see in https://kueue.sigs.k8s.io/docs/concepts/resource_flavor/#resourceflavor-taints, RF `nodeTaints` is not just nodeTaints, that works as flavor taints as well.

I meant the following reproduces the same scheduling result. However, they expect `nodeTaints` works.

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "flavor"
  nodeTaints:
  - effect: NoSchedule
    key: spot
    value: "true"
  tolerations:
  - key: spot
    operator: "Exists"
    effect: "NoSchedule"
```

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "flavor"
  tolerations:
  - key: spot
    operator: "Exists"
    effect: "NoSchedule"
```
