### ISSUE TITLE
StrictFIFO prevents borrowing when CQ has pending workloads

### ISSUE THREAD

**Issue by yuvalaz99** [kubernetes-sigs/kueue#4809]
**What happened**:

We have a CQ configured with a StrictFIFO queueing strategy.
This queue has a nominal quota that should be borrowed by another CQ when needed.

However, we've recently discovered that StrictFIFO is also affecting whether quota can be borrowed from this queue when there are pending workloads in it.

**Setup:**

Cohort Structure
--- Cohort Root (NM: 0m)
-------- ClusterQueue Guaranteed (NM: 200m)
-------- ClusterQueue BestEffort (NM: 0m)

**Event sequence leading to the Issue:**

1. Guaranteed1 (100m) -> Admitted
2. Guaranteed2 (200m) -> SchedulingGated (100m quota left)
3. BestEffort1 (100m) -> SchedulingGated. Workload have the status:
_"Workload no longer fits after processing another workload"_

**What you expected to happen**:

According to the [docs](https://kueue.sigs.k8s.io/docs/concepts/cluster_queue/#queueing-strategy)
> The queueing strategy determines how workloads are ordered in the ClusterQueue and how they are re-queued after an unsuccessful admission attempt.

We expected the queueing strategy to impact only the ordering of workloads within the queue.
We did not expect it to affect the ability of workloads from other CQs to borrow quota, which in our use case leads to major system underutilization.

This behavior is not documented anywhere. I'm wondering whether this is the expected behavior from your side?

**How to reproduce it (as minimally and precisely as possible)**:
( We are using in our setup pod integration )
1. Apply core configuration (cohorts, queues, and priority classes):
```
---
# Default Cohort
apiVersion: kueue.x-k8s.io/v1alpha1
kind: Cohort
metadata:
  name: default
---
# Guaranteed ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "guaranteed"
spec:
  namespaceSelector: {}
  queueingStrategy: StrictFIFO
  preemption:
    reclaimWithinCohort: LowerPriority
    withinClusterQueue: Never
  cohort: default
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default"
      resources:
      - name: "cpu"
        nominalQuota: "200m"
---
# Best-effort ClusterQueue
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "best-effort"
spec:
  namespaceSelector: {}
  preemption:
    reclaimWithinCohort: Never
    withinClusterQueue: Never
  cohort: default
  resourceGroups:
  - coveredResources: ["cpu"]
    flavors:
    - name: "default"
      resources:
      - name: "cpu"
        nominalQuota: "0m"
---
# LocalQueues
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: guaranteed
spec:
  clusterQueue: guaranteed
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: best-effort
spec:
  clusterQueue: best-effort
---
# Resource Flavor
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: default
---
```
2. Create guaranteed workloads:
```
# Workloads - Guaranteed
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: guaranteed-1
 labels: {app: guaranteed-1, kueue-job: "true", kueue.x-k8s.io/queue-name: guaranteed}
spec:
 replicas: 1
 selector:
   matchLabels: {app: guaranteed-1}
 template:
   metadata:
     labels: {app: guaranteed-1, kueue-job: "true", kueue.x-k8s.io/queue-name: guaranteed}
   spec:
     terminationGracePeriodSeconds: 1
     containers:
     - name: main
       image: registry.k8s.io/pause:3.9
       resources:
         requests:
           cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: guaranteed-2
 labels: {app: guaranteed-2, kueue-job: "true", kueue.x-k8s.io/queue-name: guaranteed}
spec:
 replicas: 1
 selector:
   matchLabels: {app: guaranteed-2}
 template:
   metadata:
     labels: {app: guaranteed-2, kueue-job: "true", kueue.x-k8s.io/queue-name: guaranteed}
   spec:
     terminationGracePeriodSeconds: 1
     containers:
     - name: main
       image: registry.k8s.io/pause:3.9
       resources:
         requests:
           cpu: "200m"
```
3. Create best-effort workload
```
# Workloads - Best Effort
apiVersion: apps/v1
kind: Deployment
metadata:
  name: best-effort-1
  labels: {app: best-effort, kueue-job: "true", kueue.x-k8s.io/queue-name: best-effort}
spec:
  replicas: 1
  selector:
    matchLabels: {app: best-effort}
  template:
    metadata:
      labels: {app: best-effort, kueue-job: "true", kueue.x-k8s.io/queue-name: best-effort}
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: main
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: "100m"
```
4. Expected pods status
```
NAME                                             READY   STATUS             RESTARTS          AGE
best-effort-1-789b74c4f5-2vppj                   0/1     SchedulingGated    0                 20s
guaranteed-1-7c77c5cffc-gcrp2                    1/1     Running            0                 28s
guaranteed-2-78fc659fd8-c6cpg                    0/1     SchedulingGated    0                 28s
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.30
- Kueue version (use `git describe --tags --dirty --always`): 0.10.2
- Cloud provider or hardware configuration: GCP
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
