### ISSUE TITLE
Enable to get metrics via HTTP

### ISSUE THREAD

**Issue by highpon** [kubernetes-sigs/kueue#4841]
**What would you like to be added**:
Add an option to allow metrics to be retrieved via HTTP

**Why is this needed**:
We want to retrieve metrics without HTTPS or TLS authentication.
In a closed network, it may be better not to have them.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by mimowo** [comment]
we offer metrics via https using internal certs, ootb. can you describe what is the use case for plain http? Is it improving startup time?

**Comment by highpon** [comment]
@mimowo 
Thanks for your reply!

> we offer metrics via https using internal certs, ootb. can you describe what is the use case for plain http? Is it improving startup time?

I did not intend to speed up the startup time.

I proposed this feature because I believe that Kueue users can obtain metrics in a simple configuration by supporting the ability to obtain metrics via HTTP, assuming an environment that does not require authentication, authorization, or encryption.

**Comment by mimowo** [comment]
thabks for your reply. I see, TLS is not needed in many internal networks, but wondering what is the benefit to the end users since TLS using internal certs is the default. 

Maybe even if this wasn't the original motivation it is still good for users as it reduces the amount of resources needed to generate the certs and thus the start up time.

We actually discussed this before with @tenzen-y and @kannon92 and we thought we don't need to support plain http, but I'm ok to revisit it.

**Comment by highpon** [comment]
@kannon92 
Thanks for your reply!

Surely the documentation should clearly state that it should not be recommended.
I believe that if the documentation describes the risks of enabling the option, there will be no cases of misuse by users who want to connect with TLS enabled.

However, I think there are security risks involved.
I assume that the Kueue Configuration API is used to enable/disable this functionality.
The Kueue Configuration API is managed using ConfigMap, and I think the relative risk is higher because if you can even manipulate ConfigMap, you can expose metrics information without certificate authentication/authorization.

**Comment by atosatto** [comment]
> Right now, we require that people that access the metrics endpoint must have access to the serviceAccount. But if you want to relax this, then you could say anyone can view metrics of Kueue.

I am currently running Kueue with `internalCertManagement.enabled = false` to provide Kueue with custom certificates for the webhooks. With the current implementation of secured metrics, not only we are implementing HTTPS but we are also adding AuthN/AuthZ via tokenreviews and subjectaccessreviews.

I think it would be nice to relax this constraint and allow users to configure mTLS to secure metrics scraping without adding the dependency on the Kubernetes API or allow users to meet these bespoke authN/authZ requirements via a side-car. For example `node-exporter` allows to enable mTLS via 

```yaml
tls_server_config:
  # Certificate and key files for server to use to authenticate to client.
  cert_file: "/etc/node_exporter/server.crt"
  key_file: "/etc/node_exporter/server.key"
  # Enforce mutual TLS.
  # For more detail on clientAuth options: https://golang.org/pkg/crypto/tls/#ClientAuthType
  client_auth_type: "RequireAndVerifyClientCert"
  # CA certificate for client certificate authentication to the server.
  client_ca_file: "/etc/node_exporter/root_ca.crt"
```
