### ISSUE TITLE
Workloads are not automatically removed when the LeaderWorkerSet is deleted.

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#4966]
**What happened**:
When a LeaderWorkerSet without a queue name is deleted while managedJobWithoutQueueName is set to true, the workloads are not removed.

**What you expected to happen**:

All workloads should be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

1. Apply kueue manifests with `managedJobWithoutQueueName=true`.

2. Create LeaderWorkerSet without queue-name.

```
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: nginx-leaderworkerset
  labels:
    app: nginx
spec:
  replicas: 3
  leaderWorkerTemplate:
    size: 3
    leaderTemplate:
      spec:
        containers:
          - name: nginx-leader
            image: registry.k8s.io/nginx-slim:0.27
            resources:
              requests:
                cpu: "100m"
            ports:
              - containerPort: 80
    workerTemplate:
      spec:
        containers:
          - name: nginx-worker
            image: registry.k8s.io/nginx-slim:0.27
            resources:
              requests:
                cpu: "200m"
            ports:
              - containerPort: 80
```

3. Delete LeaderWorkerSet.

```
kubectl delete lws nginx-leaderworkerset
```

4. As a result, all workloads are still here.

```
default     leaderworkerset-nginx-leaderworkerset-0-84517                                               24s
default     leaderworkerset-nginx-leaderworkerset-1-8f23f                                               24s
default     leaderworkerset-nginx-leaderworkerset-2-4fe3c                                               24s
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.32.2
- Kueue version (use `git describe --tags --dirty --always`): main branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
