### ISSUE TITLE
Can't set queue-name in LeaderWorkerSet.

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#4967]
**What happened**:

When I'm trying to set queue-name on LeaderWorkerSet with `managedJobWithoutQueueName=true` I get `field is immutable` error.

```
Error from server (Forbidden): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"leaderworkerset.x-k8s.io/v1\",\"kind\":\"LeaderWorkerSet\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"nginx\",\"kueue.x-k8s.io/queue-name\":\"user-queue\"},\"name\":\"nginx-leaderworkerset\",\"namespace\":\"default\"},\"spec\":{\"leaderWorkerTemplate\":{\"leaderTemplate\":{\"spec\":{\"containers\":[{\"image\":\"registry.k8s.io/nginx-slim:0.27\",\"name\":\"nginx-leader\",\"ports\":[{\"containerPort\":80}],\"resources\":{\"requests\":{\"cpu\":\"100m\"}}}]}},\"size\":3,\"workerTemplate\":{\"spec\":{\"containers\":[{\"image\":\"registry.k8s.io/nginx-slim:0.27\",\"name\":\"nginx-worker\",\"ports\":[{\"containerPort\":80}],\"resources\":{\"requests\":{\"cpu\":\"200m\"}}}]}}},\"replicas\":3}}\n"},"labels":{"kueue.x-k8s.io/queue-name":"user-queue"}},"spec":{"leaderWorkerTemplate":{"leaderTemplate":{"spec":{"containers":[{"image":"registry.k8s.io/nginx-slim:0.27","name":"nginx-leader","ports":[{"containerPort":80}],"resources":{"requests":{"cpu":"100m"}}}]}},"workerTemplate":{"spec":{"containers":[{"image":"registry.k8s.io/nginx-slim:0.27","name":"nginx-worker","ports":[{"containerPort":80}],"resources":{"requests":{"cpu":"200m"}}}]}}}}}
to:
Resource: "leaderworkerset.x-k8s.io/v1, Resource=leaderworkersets", GroupVersionKind: "leaderworkerset.x-k8s.io/v1, Kind=LeaderWorkerSet"
Name: "nginx-leaderworkerset", Namespace: "default"
for: "testbin/demo/sample-leaderworkerset.yaml": error when patching "testbin/demo/sample-leaderworkerset.yaml": admission webhook "vleaderworkerset.kb.io" denied the request: metadata.labels[kueue.x-k8s.io/queue-name]: Invalid value: "user-queue": field is immutable
```

**What you expected to happen**:

Allow setting the queue-name when `managedJobWithoutQueueName=true` and no queue name is specified

**How to reproduce it (as minimally and precisely as possible)**:

1. Apply kueue manifests with `managedJobWithoutQueueName=true`.

2. Create LeaderWorkerSet without queue-name.

```yaml
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: nginx-leaderworkerset
  labels:
    app: nginx
spec:
  replicas: 3
  leaderWorkerTemplate:
    size: 3
    leaderTemplate:
      spec:
        containers:
          - name: nginx-leader
            image: registry.k8s.io/nginx-slim:0.27
            resources:
              requests:
                cpu: "100m"
            ports:
              - containerPort: 80
    workerTemplate:
      spec:
        containers:
          - name: nginx-worker
            image: registry.k8s.io/nginx-slim:0.27
            resources:
              requests:
                cpu: "200m"
            ports:
              - containerPort: 80
```

3. Set queue-name on LeaderWorkerSet.

```yaml
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: nginx-leaderworkerset
  labels:
    app: nginx
    kueue.x-k8s.io/queue-name: user-queue
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.32.2
- Kueue version (use `git describe --tags --dirty --always`): main branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
