### ISSUE TITLE
The workload is not admitted if queue-name is set while manageJobsWithoutQueueName is enabled

### ISSUE THREAD

**Issue by mbobrovskyi** [kubernetes-sigs/kueue#5048]
**What happened**:

The workload is not admitted if queue-name is set while manageJobsWithoutQueueName is enabled

**What you expected to happen**:

Workload should be admitted.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install Kueue with manageJobsWithoutQueueName=true, "pod" enabled and "statefulset" enabled.
2. Apply https://github.com/kubernetes-sigs/kueue/blob/f23be17d69a548e5c279140edb6fc26e0d7d6ab0/site/static/examples/admin/single-clusterqueue-setup.yaml.
3. Create StatefulSet without queue-name:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.27
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
  serviceName: "nginx"
```

4. Apply StatefulSet with queue-name:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  labels:
    app: nginx
    kueue.x-k8s.io/queue-name: user-queue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.27
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
  serviceName: "nginx"

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  1.32.2
- Kueue version (use `git describe --tags --dirty --always`): main branch
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
