### ISSUE TITLE
GKE; The workload backoff was finished; The workload has failed admission checks; Max nodepool size reached

### ISSUE THREAD

**Issue by Smuger** [kubernetes-sigs/kueue#5129]
**Possibly the same issue**
https://github.com/kubernetes-sigs/kueue/issues/3258

**What happened**:

On a GKE cluster workloads fail admission check for jobs that had to be queue due to max nodepool size reached. I'm also using [Dynamic Workload Scheduler](https://cloud.google.com/blog/products/compute/introducing-dynamic-workload-scheduler)

We have seen this happened the most on flavors that require more than 1 GPU. The example below comes from a run with a flavor that needs x4 A100.

```
Status:
  Admission Checks:
    Last Transition Time:  2025-04-25T16:06:34Z
    Message:               Retrying after failure: Max nodepool size reached, affected nodepools: dws-a100-40gb-4x-node-pool
    Name:                  dws-prov
    State:                 Retry
  Conditions:
    Last Transition Time:  2025-04-25T16:09:23Z
    Message:               The workload has failed admission checks
    Observed Generation:   1
    Reason:                Pending
    Status:                False
    Type:                  QuotaReserved
    Last Transition Time:  2025-04-25T16:09:23Z
    Message:               At least one admission check is false
    Observed Generation:   1
    Reason:                AdmissionCheck
    Status:                True
    Type:                  Evicted
    Last Transition Time:  2025-04-25T16:10:23Z
    Message:               The workload backoff was finished
    Observed Generation:   1
    Reason:                BackoffFinished
    Status:                True
    Type:                  Requeued
  Requeue State:
    Count:       1
    Requeue At:  2025-04-25T16:10:23Z
  Resource Requests:
    Name:  main
    Resources:
      Cpu:             1250m
      Memory:          8Gi
      nvidia.com/gpu:  4
Events:
  Type     Reason   Age                   From             Message
  ----     ------   ----                  ----             -------
  Warning  Pending  14m (x89 over 3h32m)  kueue-admission  The workload has failed admission checks
```

**What you expected to happen**:
I was expecting the backoff strategy to retry admission checks for 7 days.
```yaml
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ProvisioningRequestConfig
metadata:
  name: dws-config
spec:
  provisioningClassName: queued-provisioning.gke.io
  managedResources:
  - nvidia.com/gpu
  retryStrategy:
    backoffLimitCount: 15
    backoffBaseSeconds: 60
    backoffMaxSeconds: 604800  # 7 days in seconds
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a GKE cluster with one nodepool of size 1 of a given flavor 
2. Create two jobs that need that flavor
3. When the first job finishes, the second will already be in a BackoffFinished state and will not attempt to run another admission check.

**Anything else we need to know?**:
This can be completely wrong and the cause of this problem but I'm assuming that I need to allow the nodepool to scale to a value one more than my quota. 

e.g.
`If I have a quota of [1] A100 I should set my autoscaling on my nodepool to 2`

`If I have a quota of [4] A100 and my favor needs four GPUs per box I need to set autoscaling on my nodepool to 8`

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.32.3-gke.1717000
```
- Kueue version (use `git describe --tags --dirty --always`):
```
v0.11.4 (but we saw this on v0.11.3 as well. Probably also the previous ones)
```
- Cloud provider or hardware configuration:
```
Google Cloud; A100 40GB
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=b09cce333d9e64d1404b4b56037dd2492722fa1e
GOOGLE_CRASH_ID=Lakitu
VERSION=117
VERSION_ID=117
BUILD_ID=18613.164.98
```
- Kernel (e.g. `uname -a`):
```
Linux gke-prod-n-r-training-kueue-node-pool-6334a200-6nv5 6.6.72+ #1 SMP PREEMPT_DYNAMIC Sun Mar 30 09:02:56 UTC 2025 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
```
- Install tools:
- Others:

I was also seeing errors like this one for the jobs that were failing
```json
{
  "insertId": "qftjasvb2zeu3dc9",
  "jsonPayload": {
    "error": "clearing admission: Operation cannot be fulfilled on workloads.kueue.x-k8s.io \"job-0d1fff4c41864c69b8f9fca17b7d4f73-35ffd\": the object has been modified; please apply your changes to the latest version and try again",
    "controllerKind": "Job",
    "reconcileID": "8ddad845-2f9e-49f2-ab0d-7295bd183b0d",
    "level": "error",
    "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:224",
    "controllerGroup": "batch",
    "controller": "job",
    "namespace": "default",
    "msg": "Reconciler error",
    "Job": {
      "namespace": "default",
      "name": "0d1fff4c41864c69b8f9fca17b7d4f73"
    },
    "name": "0d1fff4c41864c69b8f9fca17b7d4f73",
    "ts": "2025-04-25T16:09:23.164778584Z",
    "caller": "controller/controller.go:316"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "project_id": "n-r-training",
      "cluster_name": "prod-n-r-training-cluster-us-e1",
      "pod_name": "kueue-controller-manager-5975cbd886-56vc9",
      "namespace_name": "kueue-system",
      "container_name": "manager",
      "location": "us-east1"
    }
  },
  "timestamp": "2025-04-25T16:09:23.165111880Z",
  "severity": "ERROR",
  "labels": {
    "compute.googleapis.com/resource_name": "gke-prod-n-r-training-kueue-node-pool-6334a200-6nv5",
    "k8s-pod/app_kubernetes_io/component": "controller",
    "logging.gke.io/top_level_controller_type": "Deployment",
    "k8s-pod/control-plane": "controller-manager",
    "logging.gke.io/top_level_controller_name": "kueue-controller-manager",
    "k8s-pod/pod-template-hash": "5975cbd886",
    "k8s-pod/app_kubernetes_io/name": "kueue"
  },
  "logName": "projects/n-r-training/logs/stderr",
  "receiveTimestamp": "2025-04-25T16:09:25.369575252Z"
}
```

**Comment by kannon92** [comment]
cc @mimowo @mwielgus 

I'm not sure if this is really an upstream issue as this seems to be a GKE specific problem with the DWS admission checks.

**Comment by Smuger** [comment]
@kannon92 

Thanks for getting back to me.

I've reached out to Google about this and will share their response here in case others are experiencing the same issue.

Please correct me if I'm wrong, but I believe the admission check should still re-run even if "dws-prov" is not right?

**Comment by rlia** [comment]
I often use GKE Autopilot for Kueue validation and regularly encounter problems.

Has a ProvisioningRequest been created by Kueue? If so, what is the status?
```
$ kubectl get provisioningrequest 
$ kubectl describe provisioningrequest 
```

Also, the procedure for using DWS without Kueue could be used to see if there is a problem with GKE's DWS itself.
https://cloud.google.com/kubernetes-engine/docs/how-to/provisioningrequest#create-provisioningrequest

**Comment by jaash7zohz** [comment]
Hello @Smuger !

> I've reached out to Google about this and will share their response here in case others are experiencing the same issue.
> 
> Please correct me if I'm wrong, but I believe the admission check should still re-run even if "dws-prov" is not right?

Have you got any news from Google please (or any solution) ?
Thank you !

**Comment by Smuger** [comment]
@jaash7zohz 

Google is looking into this. It doesn’t appear to be a misconfiguration on the user’s side.

**Comment by SC-Turner** [comment]
I'm having this exact problem also. Occurs on both Kueue v0.7.0 and v0.12.3. 

Notably, deleting the workload manually will retrigger an admissionCheck for the job and the job will run (If resources are now available).

Any work arounds or solutions would be much appreciated.

**Comment by mimowo** [comment]
So, there are two things at play here, IIUC:
1. why GKE does not provision successfully the ProvisioningRequest sometimes when using `queued-provisioning.gke.io` - I would leave this issue to the GKE support team
2. why Kueue does not retry the failure, as it is expected based on the configuration:

```yaml
  retryStrategy:
    backoffLimitCount: 15
    backoffBaseSeconds: 60
    backoffMaxSeconds: 604800  # 7 days in seconds
```
Let's focus exclusively on (2.) here.

First, indeed, the status is surprising 
```yaml
Status:
  Admission Checks:
    Last Transition Time:  2025-04-25T16:06:34Z
    Message:               Retrying after failure: Max nodepool size reached, affected nodepools: dws-a100-40gb-4x-node-pool
    Name:                  dws-prov
    State:                 Retry
  Conditions:
    Last Transition Time:  2025-04-25T16:09:23Z
    Message:               The workload has failed admission checks
    Observed Generation:   1
    Reason:                Pending
    Status:                False
    Type:                  QuotaReserved
    Last Transition Time:  2025-04-25T16:09:23Z
    Message:               At least one admission check is false
    Observed Generation:   1
    Reason:                AdmissionCheck
    Status:                True
    Type:                  Evicted
```
because the AC state should be reset back to "Pending" by [ResetChecksOnEviction](
https://github.com/kubernetes-sigs/kueue/blob/74a9dfc91cc1caf7a0ddb283e2972cd49de32e02/pkg/controller/core/workload_controller.go#L398-L399) on eviction which happened at `2025-04-25T16:09:23Z`.

So, the puzzle is - why during eviction the admission check was not flipped to "Pending" - I believe this is what is blocking the re-admission.

To help us understand the issue:
- does this happen on every run or flakes?
- does it trigger re-admission if you manually flip workload.Status.AdmissionChecks.State to pending? eg. using `kubectl edit wl/<wl-name> --subresource=status`
- can you provide full kueue logs, grepped by the workload name at the level of V(3)?
