### ISSUE TITLE
Expose TAS detected topology domains

### ISSUE THREAD

**Issue by avrittrohwer** [kubernetes-sigs/kueue#5147]
**What would you like to be added**:

Have the ability for Kueue to expose TAS detected topology domains.  For example, with TAS config:

```
apiVersion: kueue.x-k8s.io/v1alpha1
kind: Topology
metadata:
  name: "default"
spec:
  levels:
  - nodeLabel: "cloud.provider.com/topology-rack"
  - nodeLabel: "kubernetes.io/hostname"
---
kind: ResourceFlavor
apiVersion: kueue.x-k8s.io/v1beta1
metadata:
  name: "tas-flavor"
spec:
  nodeLabels:
    cloud.provider.com/node-group: "tas-node-group"
  topologyName: "default"
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "tas-cluster-queue"
spec:
  resourceGroups:
  - coveredResources: ["nvidia.com/gpu"]
    flavors:
    - name: "tas-flavor"
      resources:
      - name: "nvidia.com/gpu"
        nominalQuota: 64
```

Deployed in a cluster with 2 racks of 4 nodes, each node having 8 GPUs, Kueue could expose:

```
detectedTopologies:
- clusterQueueName: "tas-cluster-queue"
  resourceFlavors:
  - name: "tas-flavor"
    levels:
    - nodeLabel: "cloud.provider.com/topology-rack"
      domains:
      - labelValue: "rack-0"
        nodes: 4
        availableQuota: 32
      - labelValue: "rack-1"
        nodes: 4
        availableQuota: 32
    - nodeLabel: "kubernetes.io/hostname"
      domains:
      - labelValue: "rack-0-node-0"
        nodes: 1
        availableQuota: 8
      - labelValue: "rack-0-node-1"
        nodes: 1
        availableQuota: 8
        ...
      - labelValue: "rack-1-node-3"
        nodes: 1
        availableQuota: 8
```

If rack-0-node-0 became unhealthy:

```
detectedTopologies:
- clusterQueueName: "tas-cluster-queue"
  resourceFlavors:
  - name: "tas-flavor"
    levels:
    - nodeLabel: "cloud.provider.com/topology-rack"
      domains:
      - labelValue: "rack-0"
        nodes: 4
        availableQuota: 24
      - labelValue: "rack-1"
        nodes: 4
        availableQuota: 32
    - nodeLabel: "kubernetes.io/hostname"
      domains:
      - labelValue: "rack-0-node-0"
        nodes: 1
        availableQuota: 0
      - labelValue: "rack-0-node-1"
        nodes: 1
        availableQuota: 8
        ...
      - labelValue: "rack-1-node-3"
        nodes: 1
        availableQuota: 8
```

If rack-0-node-0 unregistered from the cluster:

```
detectedTopologies:
- clusterQueueName: "tas-cluster-queue"
  resourceFlavors:
  - name: "tas-flavor"
    levels:
    - nodeLabel: "cloud.provider.com/topology-rack"
      domains:
      - labelValue: "rack-0"
        nodes: 3
        availableQuota: 24
      - labelValue: "rack-1"
        nodes: 4
        availableQuota: 32
    - nodeLabel: "kubernetes.io/hostname"
      domains:
      - labelValue: "rack-0-node-1"
        nodes: 1
        availableQuota: 8
        ...
      - labelValue: "rack-1-node-3"
        nodes: 1
        availableQuota: 8
```

**Why is this needed**:

This feature would help Kueue Admins ensure TAS is detecting the intended topology domains and would help aid in debugging workloads not getting admitted due to fewer nodes detected than expected  (unhealthy node, misconfigured topology labels, etc).  It would also enable better visualization of detected topologies and their utilization by tools like kueue-viz.

**Completion requirements**:

1. **Decide where the information should be exposed**:  This API has the potential to return very large responses in clusters with lots of nodes that use  kubernetes.io/hostname as a topology level.  It is likely infeasible to put this information in ClusterQueue status due to etcd object size limitations.  This seems a good candidate for an on-demand API like the Pending Workloads on-demand API: https://kueue.sigs.k8s.io/docs/tasks/manage/monitor_pending_workloads/pending_workloads_on_demand/
2. **Decide on supported query parameters**: Give the potential for large API responses, we should support filtering returned TAS information to specific cluster queues, topology levels, any other?
3. **Decide the response format**: in my above examples I had a flat hierarchy based on topology level.  An alternative could be a tree hierarchy like:
   ```
   detectedTopologies:
   - clusterQueueName: "tas-cluster-queue"
     resourceFlavors:
     - name: "tas-flavor"
       levels:
       - nodeLabel: "cloud.provider.com/topology-rack"
         domains:
         - labelValue: "rack-0"
           nodes: 4
           availableQuota: 32
           subLevels:
           - nodeLabel: "kubernetes.io/hostname"
             domains:
             - labelValue: "rack-0-node-0"
               nodes: 1
               availableQuota: 8
               ...
             - labelValue: "rack-0-node-3"
               nodes: 1
               availableQuota: 8
         - labelValue: "rack-1"
           nodes: 4
           availableQuota: 32
           subLevels:
           - nodeLabel: "kubernetes.io/hostname"
             domains:
             - labelValue: "rack-1-node-0"
               nodes: 1
               availableQuota: 8
               ...
             - labelValue: "rack-1-node-3"
               nodes: 1
               availableQuota: 8
   ```
4. **Decide on response information**: the API could also return what workloads are reserving quota.  Would this be useful?

This enhancement requires the following artifacts:

- [X] Design doc
- [X] API change
- [X] Docs update

The artifacts should be linked in subsequent comments.
