### ISSUE TITLE
Can't change workload priority class of deployment

### ISSUE THREAD

**Issue by Gab-Menezes** [kubernetes-sigs/kueue#5148]
**What happened**: The label `kueue.x-k8s.io/priority-class` is immutable for deployments.

**What you expected to happen**: Be able to change the workload priority of a deployment.

The [docs](https://kueue.sigs.k8s.io/docs/reference/labels-and-annotations/#kueuex-k8siopriority-class) say:
> The label key in the workload holds the workloadPriorityClass name. This label is always mutable, as it may be useful for preemption...

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    kueue.x-k8s.io/queue-name: user-queue
    kueue.x-k8s.io/priority-class: dev-priority # <-- try to change this
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.27
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
```

Gives you the following error:
```
Error from server (Forbidden): error when applying patch:
<redacted>
to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "<redacted>", Namespace: "default"
for: "<redacted>": error when patching "<redacted>": admission webhook "vdeployment.kb.io" denied the request: metadata.labels[kueue.x-k8s.io/priority-class]: Invalid value: "<redacted>": field is immutable
```

**Anything else we need to know?**: No

**Environment**:
- Kubernetes version (use `kubectl version`): 1.31.2
- Kueue version (use `git describe --tags --dirty --always`): 0.11.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
