### ISSUE TITLE
ApiService-FailedDiscoveryCheck

### ISSUE THREAD

**Issue by milosbw** [kubernetes-sigs/kueue#5150]
**What happened**:
Tried to install kueue v0.11.4 , went well but I am facing some problem with ApiService.

**What you expected to happen**:
Everything to be up&running (without any errors) after 'helm install kueue'...

**How to reproduce it (as minimally and precisely as possible)**:
I just ran the helm install in my EKS cluster:
```sh
helm install kueue oci://registry.k8s.io/kueue/charts/kueue \
  --version=0.11.4 \
  --namespace  kueue-system \
  --create-namespace \
  --wait --timeout 300s
```
I checked k8s resources, everything is up&running besides 'ApiService' - **FailedDiscoveryCheck**

**Anything else we need to know?**:

```sh
k get apiservice v1beta1.visibility.kueue.x-k8s.io -o yaml
```

```yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2025-05-02T19:50:11Z"
  labels:
    app.kubernetes.io/instance: kueue
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kueue
    app.kubernetes.io/version: v0.11.4
    argocd.argoproj.io/instance: kueue
    control-plane: controller-manager
    helm.sh/chart: kueue-0.11.4
  name: v1beta1.visibility.kueue.x-k8s.io
  resourceVersion: "5997837"
  uid: cdc7c7c2-9e6d-4291-822c-4a11d0876045
spec:
  group: visibility.kueue.x-k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: kueue-visibility-server
    namespace: kueue-system
    port: 443
  version: v1beta1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2025-05-02T19:50:11Z"
    message: 'failing or missing response from https://<IP>:8082/apis/visibility.kueue.x-k8s.io/v1beta1:
      Get "https://<IP>:8082/apis/visibility.kueue.x-k8s.io/v1beta1": context
      deadline exceeded'
    reason: FailedDiscoveryCheck
    status: "False"
    type: Available
```
There are no errors in kueue-controller-manager pod's log.

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: v1.32.3-eks-4096722
- Kueue version (use `git describe --tags --dirty --always`): v0.11.4
- Cloud provider or hardware configuration: AWS EKS(arm based)
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
I guess that this is a Helm manifests generation problem. We need to check if Helm generate intended manifests.

**Comment by milosbw** [comment]
@tenzen-y 
I am facing the same behavior with the 'kubectl apply':
```sh
kubectl apply --server-side -f https://github.com/kubernetes-sigs/kueue/releases/download/v0.11.4/manifests.yaml
```

This is defined ApiService manifest:

```yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: kueue
    control-plane: controller-manager
  name: v1beta1.visibility.kueue.x-k8s.io
spec:
  group: visibility.kueue.x-k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: kueue-visibility-server
    namespace: kueue-system
  version: v1beta1
  versionPriority: 100
```

From helm(seems fine too):
```yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
  {{- include "kueue.labels" . | nindent 4 }}
  name: v1beta1.visibility.kueue.x-k8s.io
spec:
  group: visibility.kueue.x-k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: '{{ include "kueue.fullname" . }}-visibility-server'
    namespace: '{{ .Release.Namespace }}'
  version: v1beta1
  versionPriority: 100
```

**Comment by tenzen-y** [comment]
@milosbw Thank you for letting me know. Do you see the same errors as the Helm installation?

cc: @PBundyra

**Comment by milosbw** [comment]
> [@milosbw](https://github.com/milosbw) Thank you for letting me know. Do you see the same errors as the Helm installation?
> 
> cc: [@PBundyra](https://github.com/PBundyra)

Yes. The very same error.

**Comment by mbobrovskyi** [comment]
Interesting. I tried running it both on Kind and on a real GKE cluster – it seems to be working fine. Unfortunately, I don’t have an AWS account to test it on EKS.

However, when the `kueue-controller-manager` is initializing, I encountered the following error:

```yaml
status:
  conditions:
  - lastTransitionTime: "2025-05-06T11:40:10Z"
    message: endpoints for service/kueue-visibility-server in "kueue-system" have
      no addresses with port name "https"
    reason: MissingEndpoints
    status: "False"
    type: Available
```

Once the `kueue-controller-manager` is fully running:

```yaml
status:
  conditions:
  - lastTransitionTime: "2025-05-06T11:42:00Z"
    message: all checks passed
    reason: Passed
    status: "True"
    type: Available
```
