### ISSUE TITLE
TAS: Resource Fragmentation Causing Admitted/Unschedulable Workload Despite Hostname Level Tag

### ISSUE THREAD

**Issue by saad-essential** [kubernetes-sigs/kueue#5243]
**What happened**: At a high level, despite having `podset-preferred-topology` at `kubernetes.io/hostname` for my PodSet's, I was able to have a high-priority full-node Workload admitted when it is impossible for it to be scheduled on any node. 

Specifically:
1. Our cluster has 4 nodes, each with 8 GPU's. Our resourceFlavor tracks GPU resources, and has a topology defined below.
2. I scheduled 6 high-priority Workload's on each Node, where each Workload needs 1 GPU.
3. I also scheduled 8 low-priority Workload's. Because each of our 4 nodes had 2 GPU's free after Step 2, these Workload's were evenly divided across the nodes (2 low-priority Workload's on each of the 4 nodes)
4. I then scheduled 1 high-priority Workload that needs 8 GPU's. I soon saw the 8 pods running low-priority Workloads get Terminated. The high-priority Workload was then admitted, and I see a pod needing 8 GPU's stuck in Pending state.. Because the 8 freed GPU's from pre-emption were distributed across multiple nodes, the high-priority pod can not be scheduled.
5. I then scheduled 1 high-priority Workload that needs 1 GPU. This Workload cannot get admitted, even though technically my farm has 8 GPU's completely idle. The high-priority Workload scheduled in Step 4 is blocking everything below.

**What you expected to happen**:
I expected the Workload scheduled in Step 4 to not be admitted into the queue since I thought Topology Aware Scheduling takes into account the hosts that the pods are getting evicted from.

**How to reproduce it (as minimally and precisely as possible)**:
Repeat Steps 1-5 mentioned above.

**Anything else we need to know?**:
Below are some of my k8s YAML's, let me know if you need more. 

_Topology YAML_
```
apiVersion: kueue.x-k8s.io/v1alpha1
kind: Topology
metadata:
  name: "amd-topology"
spec:
  levels:
  - nodeLabel: "kubernetes.io/hostname"
```

_ResourceFlavor YAML_
```
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: infra-test
spec:
  nodeLabels:
    kueue-pool: infra-test
    amd.com/gpu: mi300x
    amd.com/gpu-count: "8"
    amd.com/gpu-memory: "192Gi"
  topologyName: amd-topology
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
> kubectl version
Client Version: v1.31.6-dispatcher
Kustomize Version: v5.4.2
Server Version: v1.31.5+rke2r1
```
- Kueue version (use `git describe --tags --dirty --always`):
```
> kubectl describe pod kueue-controller-manager-7fc9b7b4d4-2kkt5 -n kueue-system | grep registry.k8s.io/kueue/kueue
    Image:         registry.k8s.io/kueue/kueue:v0.10.0
```
