### ISSUE TITLE
[Discussion]: In Place Pod Resizing and Kueue

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/kueue#5257]
Kubernetes has a feature called in place pod resizing which would relax immutability of pods. Users can be able to resize pods for core resources.

I think this could be a potential way to bypass Kueue quota.

Imagine the following scenario:

a) User admits a workload with low memory/cpu requests.
b) workload is admitted and scheduled.
c) User resizes workload to much larger memory/cpu request.
d) Workload will use more resources than Kueue admitted.

This is maybe less of a concern for cpu/memory but I think this could be a bigger issue if/when in place provides support for extended resources (people could get more gpus than Kueue allows).

## Short Term Fixes

We could document that in place pod resizing and Kueue will not play nice together and recommend disabling resize resource for batch-users?

## Long Term Fixes

Maybe Kueue should be aware of resizing requests and evict the workload and readmit?

**Comment by kannon92** [comment]
cc @tallclair as in place pod SME.

**Comment by mimowo** [comment]
cc @mwielgus @mwysokin

**Comment by mwysokin** [comment]
@kannon92 @tenzen-y @mimowo What if we re-adjust and the proposed long-term fix would become a middle-term one and a proper long-term fix would be in-place quota adjustment to reflect the pod resize request?

Would that be even possible considering the current implementation of quota assignment?

**Comment by mimowo** [comment]
> What if we re-adjust and the proposed long-term fix would become a middle-term one and a proper long-term fix would be in-place quota adjustment to reflect the pod resize request?

Indeed, evicting and re-admitting the workload might be already working (could you check @kannon92 ?). I think it would work, because Kueue has a generic mechanism of comparing the recorded PodTemplate (at the moment of admission) in the workload object with the PodTemplate when the job is running. If there are changes, the workload gets evicted to prevent changes post admitting.

I also think that the long-term solution would be to somehow adjust quota without preempting the workload. Scale down looks relatively easy.

**Comment by kannon92** [comment]
So to be clear, this would only impact naked pod integration ATM. I don't think workloads (Job, Deployment, StatefulSet) have relaxed the immutability of PodTemplate.

I thought we wouldn't reschedule pod workloads? If a pod gets evicted then it would not be recreated unless it was part of workload?

**Comment by kannon92** [comment]
@iholder101 brought this up to sig-node on May 20th.

**Comment by kannon92** [comment]
@mimowo is correct. It looks like kueue removes a pod if spec is different from what it expects.

reproduction:

```yaml
apiVersion: v1
kind: Pod
metadata:
  generateName: kueue-sleep-
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  containers:
  - name: nginx
    image: registry.k8s.io/nginx-slim:0.27
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "1G"
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired # Default, but explicit here
    - resourceName: memory
      restartPolicy: RestartContainer
  restartPolicy: OnFailure
```

Using kubernetes 1.33 with kubectl 1.33,

Pod is scheduled and running.

I then run `kubectl patch pod kueue-sleep-cj6vh --subresource resize --patch '{"spec":{"containers":[{"name":"nginx", "resources":{"requests":{"memory":"2G"}, "limits":{"memory":"2G"}}}]}}'`

I see the following events:

```
2s          Normal    Created                   pod/kueue-sleep-cj6vh                  Created container: nginx
2s          Normal    Started                   pod/kueue-sleep-cj6vh                  Started container nginx
3s          Normal    Killing                   pod/kueue-sleep-cj6vh                  Container nginx resize requires restart
2s          Normal    Stopped                   pod/kueue-sleep-cj6vh                  No matching Workload; restoring pod templates according to existent Workload
2s          Normal    DeletedWorkload           pod/kueue-sleep-cj6vh                  Deleted not matching Workload: default/pod-kueue-sleep-cj6vh-52863
2s          Normal    Killing                   pod/kueue-sleep-cj6vh                  Stopping container nginx
```
```
