### ISSUE TITLE
Opt-in namespace approach for Kueue for all workloads

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/kueue#5260]
**What would you like to be added**:

Provide a way for opt-in namespace approach for Kueue.

Expand `managedJobsNamespaceSelector` for all workloads.

**Why is this needed**:

For our openshift deployment of Kueue, we found that the only "safe" way to enable Kueue is only allow Kueue to manage resources in labeled namespaces for Kueue.

We find that there are admin namespaces and user namespaces. An admin namespace may be deploying operators/CRDs/Jobs and we do not want Kueue interfering with these resources. Namespaces are also dynamic.

For Openshift AI and MLBatch (IBM based Openshift AI) we find it is difficult to enable the Job integration. Many projects use batch jobs and these can be critical services like NFD or GPUOperator and we want to exclude kueue management from those.

In these projects we had to disable the batchJob integration as there is not a way to safely exclude batch jobs if you enable kueue to manage all batch jobs.

**Existing Issues**:

- https://github.com/kubernetes-sigs/kueue/issues/5244
- https://github.com/kubernetes-sigs/kueue/issues/4141

**Proposal**
I think this should be defined in a KEP but I wanted to sketch the idea here.

Expand `managedJobsNamespaceSelector` for all workloads.

It is true that if a user does not set `ManagedJobsWithoutQueueName=true`, then there will be a label present on a workload. This could be used in the webhook labelSelector but this does not help thouse who want kueue to manage all batch jobs.

Kueue has a clear idea how to do this via pod based integrations (namespaceSelector with `managedJobsWithoutNamespaceSelector`).

So our following setup:

a) Kueue based namespaces get labeled with a `managed-by-kueue: true` (naming TBD).
b) We set the `namespaceSelector` on all webhooks.
c) Webhooks only operate on namespaces with this label.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by kannon92** [comment]
Right now, webhooks for suspend based workloads do not use a namespaceSelector for the webhook.

So I can probably experiment with this on my internal operator and I will have to do this.

Right now, the problem I have is that if I use a Job, kueue will manage any job that has the KueueName label. And even if a Job does not have the label, Kueue's webhooks are still used. 

For example, deployments webhook manifest:

```yaml
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: '{{ include "kueue.fullname" . }}-webhook-service'
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-apps-v1-deployment
    name: mdeployment.kb.io
    {{- if has "deployment" $integrationsConfig.frameworks }}
    failurePolicy: Fail
    {{- else }}
    failurePolicy: Ignore
    {{- end }}
    namespaceSelector:
      {{- if (hasKey $managerConfig "managedJobsNamespaceSelector") -}}
        {{- toYaml $managerConfig.managedJobsNamespaceSelector | nindent 6 -}}
      {{- else }}
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - '{{ .Release.Namespace }}'
      {{- end }}
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deployments
    sideEffects: None
    reinvocationPolicy: '{{ .Values.mutatingWebhook.reinvocationPolicy }}'
```

While suspend based (jobs, kubeflow, JobSet, etc):

```yaml
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: '{{ include "kueue.fullname" . }}-webhook-service'
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-batch-v1-job
    failurePolicy: Fail
    name: mjob.kb.io
    rules:
      - apiGroups:
          - batch
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - jobs
    sideEffects: None
    reinvocationPolicy: '{{ .Values.mutatingWebhook.reinvocationPolicy }}'
```
