### ISSUE TITLE
Failed to watch *v1.RuntimeClass

### ISSUE THREAD

**Issue by jaym** [kubernetes-sigs/kueue#564]
**What happened**:
When using GKE with sandboxed nodes, and attempting to schedule into a gvisor sandbox using `runtimeClassName=gvisor`, kueue starts reporting this error every 30 seconds:
```
"pkg/mod/k8s.io/client-go@v0.25.6/tools/cache/reflector.go:169: Failed to watch *v1.RuntimeClass: unknown (get runtimeclasses.node.k8s.io)"
```

**What you expected to happen**:
That error not to be printed

**How to reproduce it (as minimally and precisely as possible)**:
Create a job with `runtimeClassName` set to `gvisor` on a GKE cluster with a sandboxed node.

**Anything else we need to know?**:
Applying this manifest fixes things up:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kueue-manager-role-runtimeclass
rules:
- apiGroups:
  - node.k8s.io
  resources:
  - runtimeclasses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kueue-manager-rolebinding-runtimeclass
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kueue-manager-role-runtimeclass
subjects:
- kind: ServiceAccount
  name: kueue-controller-manager
  namespace: kueue-system
```

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7-gke.900", GitCommit:"e35c4457f66187eff006dda6d2c0fe12144ef2ec", GitTreeState:"clean", BuildDate:"2022-10-26T09:25:34Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Kueue version (use `git describe --tags --dirty --always`): `v0.3.0-devel-253-g2d3f81a`. Also happens on the released `v0.2.1`
- Cloud provider or hardware configuration:
  - GKE with Sandboxed node
