### ISSUE TITLE
Kueue deletes workloads for jobs with limits, but no requests

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#590]
**What happened**:

Kueue creates and deletes in a loop (the cycle is <1s) a workload for a job with limits, but without requests.

**What you expected to happen**:

Kueue does not delete the workloads and allows the jobs to complete.

**How to reproduce it (as minimally and precisely as possible)**:

0. Setup Kueue with the `main` local queue
1. Create a job from the yaml
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job-longrun-only-limits
  annotations:
    kueue.x-k8s.io/queue-name: main
spec:
  suspend: true
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: job-longrun
        image: centos:7
        resources:
          limits:
            cpu: 100m
            memory: "200Mi"
        command: ["bash"]
        args: ["-c", 'sleep 120 && echo "Hello world"']
        imagePullPolicy: IfNotPresent
  backoffLimit: 0
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master (before 1.27)
- Kueue version (use `git describe --tags --dirty --always`): master (before 0.3.0)
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
