### ISSUE TITLE
Support flux-operator

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#716]
**What would you like to be added**:

Support queuing of ephemeral and persistent mini-clusters from [flux-operator](https://flux-framework.org/flux-operator/).

It is possible that this works out-of-the-box, given that flux-operator uses the Job API to launch Pods.

If it works, we need to document any implications.
If it doesn't work, maybe we need to add a suspend flag and a translation controller.

**Why is this needed**:

To accommodate multiple HPC researchers in a kubernetes cluster

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [x] Docs update

The artifacts should be linked in subsequent comments.

**Comment by alculquicondor** [comment]
cc @vsoch

**Comment by vsoch** [comment]
Will take a look at this! I haven't used kueue before, looking forward to trying it!

**Comment by vsoch** [comment]
@trasc can I help with this, or in assigning yourself are you saying you will do it? I'd love to try it and learn about kueue, etc.

**Comment by alculquicondor** [comment]
@trasc, for context, @vsoch is one of the maintainers of flux-operator.
We discussed offline and she agreed to help with any questions you might have.

**Comment by vsoch** [comment]
@trasc happy to help with questions and test out what you do. Please ping me anytime you want to chat!

**Comment by trasc** [comment]
Sure @vsoch ,  Thanks.

**Comment by trasc** [comment]
The big picture looks good, in the sense  that to have a minicluster work scheduled by Kueue you just need to specify the localQueue name in the jobLabels spec.

So a set of miniclusters created with 

```yaml
apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  generateName: flux-sample-kueue-
spec:
  size: 1
  containers:
    - image: ghcr.io/flux-framework/flux-restful-api:latest
      command: echo hello world 
      resources:
        requests:
          cpu: 4
          memory: "200Mi"
  jobLabels:
    kueue.x-k8s.io/queue-name: user-queue
```
will run two at a time while using `config/samples/single-clusterqueue-setup.yaml`

However I see two more or less minor issues:

1.  the `...-cert-generator` pod is running outside of the minicluster job and cannot be scheduled by kueue.
2.  in some configurations (` size: 2`  in the above config) the minicluster job never ends, this will block the cluster queue resource quota.  

The resource requests can also be easily specified in minicluster spec.

cc: @alculquicondor @vsoch
