### ISSUE TITLE
Document how to use MPIJobs with Kueue

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#764]
It should be very similar to the documentation for Flux MiniClusters

**Comment by kannon92** [comment]
I'm doing a bit more research into Kueue and I'd like to work on this.

I am running into some trouble with getting Kueue to work with MPIOperator.

**Comment by kannon92** [comment]
So I basically took the pi example from MPIOperator:

```
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: pi
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 60
    suspend: true
...
```
I apply the simple CQ/Q yaml in config/samples but I see that my MPIJob stays in suspended.  Is there anything else I am missing?  

I used 0.3.0 release of Kueue.

**Comment by tenzen-y** [comment]
@kannon92 Have you uncomment the below?

https://github.com/kubernetes-sigs/kueue/blob/cd747c596b2b56929c71abe7c6f94ab5c73609f9/config/components/manager/controller_manager_config.yaml#L33

**Comment by tenzen-y** [comment]
Actually, I'm using the following manifests :)

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kueue-system
resources:
- https://github.com/kubernetes-sigs/kueue/releases/download/v0.3.1/manifests.yaml
configMapGenerator:
- namespace: kueue-system
  name: kueue-manager-config
  behavior: replace
  files:
  - controller_manager_config.yaml
```

```yaml
apiVersion: config.kueue.x-k8s.io/v1beta1
kind: Configuration
....
controller:
  groupKindConcurrency:
    Job.batch: 5
    MPIJob.kubeflow.org: 5
...
integrations:
  frameworks:
  - "batch/job"
  - "kubeflow.org/mpijob"
```
