### ISSUE TITLE
ClusterQueue update events continue to fire forever

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#902]
**What happened**:
`ClusterQueueStatus.flavorsUsage.resources` with random order continues to fire ClusterQueue update events forever, and the number of reconciles will explode.
Therefore kueue-controller-manager much increases the load of kube-apiserver and etcd.

**What you expected to happen**:
ClusterQueues aren't updated if the old and the new ones have the same usage.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.25
- Kueue version (use `git describe --tags --dirty --always`): v0.3.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
The problem part: https://github.com/kubernetes-sigs/kueue/blob/b4635731cad8ec334d622ff4db60bfe1fbc13f77/pkg/cache/cache.go#L867-L881

**Comment by alculquicondor** [comment]
Are we triggering a reconcile even if the usage didn't change?

**Comment by tenzen-y** [comment]
> Are we triggering a reconcile even if the usage didn't change?

Yes.
if ClusterQueueStatus.flavorsUsage.resources are changes, it fires update event.

For example, in the following diffs fire update event:

```yaml
status:
...
  flavorsUsage:
  - name: foo
    resources:
    - borrowed: "0"
      name: "cpu"
      total: "4"
    - borrowed: "0"
      name: "memory"
      total: "4"
```

```yaml
status:
...
  flavorsUsage:
  - name: foo
    resources:
    - borrowed: "0"
      name: "memory"
      total: "4"
    - borrowed: "0"
      name: "cpu"
      total: "4"
```

**Comment by tenzen-y** [comment]
This issue will often happen in the HPC cluster. Because in HPC cluster, pods have multiple SR-IOV Virtual functions in resources.Resources like this:

```yaml
resources:
  requests:
    cpu: 256
    memory: 512Gi
    example.com/gpu: 8
    example.com/vf-0: 1
    example.com/vf-1: 1
    example.com/vf-2: 1
    example.com/vf-3: 1
    example.com/vf-4: 1
    example.com/vf-5: 1
    example.com/vf-6: 1
    example.com/vf-7: 1
```
